### PR TITLE
Fixes/#725 missing dependencies

### LINKED ISSUE #725: Missing dependencies in some tasks
HTS.demand-profile-generator is missing ERA5 dependency
society_prognosis.zensushousehold is missing table society.egon_destatis_zensus_household_per_ha
chp.insert-chp-egon2035 is missing openstreetmap.osm_landuse

### PR DESCRIPTION
**Pull request by IlkaCu**
Fixes #725 . 

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend-v2`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by IlkaCu** [comment]
@gnn: I added the missing dependencies, but due to lack of time I could not test it yet.

**Review by gnn — APPROVED** [review]

**Review by gnn — APPROVED** [review]
Since this is not just an insert of a missing dependency but a dependency change, a small explanatory comment in the commit message would've been nice. Saves the reviewer from having to go into the datasets and understand the individual tasks. (Which I didn't do, because I trust you know what you're doing. ;) )

**Comment by gnn** [comment]
So, the full run has one really weird [failure][0] for `industrial_gas_demand.download-industrial-gas-demand`. I've never seen that one before and there are several possible reasons for this. I'm going to investigate this one in more detail. I restarted the task, but it fails with the same error. I'm going to wait until every other task finishes before trying to restart it again. Meanwhile the `scenario_parameters.download-pypsa-technology-data` task is now running for more than 18 hours. I took the liberty of restarting that one, too, and it finished successfully in less than a minute.

The SH run has only one [failure][1]: `chp.extension-SH. Since this one is due to an undefined table, I suspect another missing dependency creating a table. I also restarted that task and it finished without problems after the restart.

[0]: https://gist.github.com/gnn/4742b0d2b164a6c9cf379030a3c93a80#file-720c5d5-de-industrial_gas_demand-download-industrial-gas-demand-01-log
[1]: https://gist.github.com/gnn/4742b0d2b164a6c9cf379030a3c93a80#file-720c5d5-sh-chp-extension-sh-01-log

**Comment by IlkaCu** [comment]
> The SH run has only one [failure](https://gist.github.com/gnn/4742b0d2b164a6c9cf379030a3c93a80#file-720c5d5-sh-chp-extension-sh-01-log): `chp.extension-SH`. Since this one is due to an undefined table, I suspect another missing dependency creating a table. I also restarted that task and the task as well as the whole DAG finished without problems after the restart.

Seems to be a missing dependency to the `IndustrialDemandCurves` dataset

**Comment by IlkaCu** [comment]
I won't be able to fix the missing dependencies mentioned above today - @gnn: Would you take care?

**Comment by gnn** [comment]
> I won't be able to fix the missing dependencies mentioned above today - @gnn: Would you take care?

Done. And I also started new runs. They're looking good so far. They're not done yet, but the early failures and stalling tasks are already done so I'd dare to live dangerous and merge these fixes into `dev`, bringing `dev` and the CI branch to the same state. Then ppl can start merging the features they want into the CI branch and I can start another weekend run once the current run finishes without any unexpected errors. Does that sound OK for you, @IlkaCu?

**Comment by IlkaCu** [comment]
Sounds good!

**Comment by IlkaCu** [comment]
@gnn: Will you inform the others?

**Comment by gnn** [comment]
The CI branch ran successfully for `Everything` and `Schleswig-Holstein` with these commits, so I merged them into `dev`. I made the exception doing a fast-forward instead of using an explicit merge commit, so that `dev` and `continuous-integration/run-everything-over-the-weekend` have a new common ancestor.

**Pull request merged**
