### PR TITLE
Features/#474 insert hydrogen infrastructure

### LINKED ISSUE #474: Insert hydrogen infrastructure

### LINKED ISSUE #515: Missing crs on hvmv_substation_voronoi table in CI
An error message is thrown when reading the hvmv_substation_voronoi table:

```
Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/hydrogen_etrago/storage.py", line 267, in calculate_and_map_saltcavern_storage_potential
    substation_voronoi = db.select_geodataframe(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/db.py", line 205, in select_geodataframe
    gdf = gpd.read_postgis(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1275, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/geopandas/geoseries.py", line 1120, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/geopandas/array.py", line 763, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
```

The `db.select_geodataframe` method complains about missing crs. QGIS, however, shows that the table 
has a crs specified (`epsg=4326`). Any idea, where this error message comes from? It is caused by the task `hydrogen_etrago.storage.calculate-and-map-saltcavern-storage-potential` when reading the substation voronoi data. This did not happen on my machine and it did not happen on last week's run (the failing task was due to the geopandas version issue #504, but after manually fixing that, the task ran smoothly).

### LINKED ISSUE #522: The updated saline structurual data is available
I received a shapefile containing the data shown in the figure 7-1 of the report (see below).

grafik

We can filter the data according to the categories of the legend supplied, therefor an update should be made. I suggest first merging #478 and updating in a new pull request.

I was not (not yet) able to find the data with the respective storage potential assessment information (eligibleor not, no numbers) in the download center of the bgr, therefore we might need to request permission to upload the shapefile to the databundle.

### LINKED ISSUE #528: Move gas related scripts from processing to datasets folder
Please move the scripts

- [gas_areas.py](https://github.com/openego/eGon-data/blob/dev/src/egon/data/processing/gas_areas.py)
- [power_to_h2.py](https://github.com/openego/eGon-data/blob/features/%23527-move-plotting-function-to-district-heating-dataset/src/egon/data/processing/power_to_h2.py)

from the processing to the datasets folder and adjust the scripts accordingly.

### LINKED ISSUE #560: The gas voronoi creation fails with buses inserted outside of German borders
After adding the eGon100RE bus data for the European neighbors (from pypsa-eur-sec), the gas_areas.create-voronoi tasks fail. The gas voronois should be created based on the buses in Germany only, therefore we need to exclude the European neighbor buses from buses to create the voronois on. At the moment, we can do this by filtering for 'eGon2035' in the scn_name column, this will however only work temporarily.

I have two solutions in mind:
- We rename carrier of the gas buses of European neighbors to something like `H2_FR`, `H2_BE`, .... This way, we can filter for scn_name and carrier.
- After filtering the buses for scn_name we add a routine to check which of those buses are in Germany and which not.

What do you think @AmeliaNadal, @ClaraBuettner, @ulfmueller, @IlkaCu? Rocket emoji for first solution, thumbs up for second solution, comment for other solution :).

### PR DESCRIPTION
**Pull request by fwitte**
Resolve #474
Resolve #515 
Resolve #522 
Resolve #528 
Resolve #560 

<del>This branch will insert hydrogen infrastructure in the eGon2035 scenario. It includes the commits from #405 as there are interdependencies to the changes introduced there.</del> #405 was merged into dev

# ToDo
- <del>1. make sure ids are not duplicated (see #514)</del> No priority, will be handeled in #520
- <del>2. e_nom_max parameter is missing for H2 overground steel tank storage</del> optional for now
- [x] 3. e_nom_max parameter for H2 underground seems excessively large
- [x] 4. the storage potential values from the InSpEE-DS report do not differentiate between Lower Saxony/Bremen and Schleswig-Holstein/Hamburg.
- [x] 5. successfully run on CI branch
- [x] 6. move hydrogen related scripts to hydrogen_etrago #528
- [x] 7. update scripts to work with updated saline structure data (will run on CI only, if databundle is updated before the weekend!)

# 1.
With tasks running simulteanous it sometimes happens, that the tasks try to insert the same ids for for different objects into the DB, e.g. overground and underground storage.

# 2.
Define a reasonable maximum value, this can also be done at a later point in time.

# 3. 
The full size storage capacity (if the inflation around a substations fully overlays a saltstructure) should be equal in these two pictures below.

grafik
Storage capacity on the CI branch run

grafik
Storage capacity on the local run

The issue is, that the same overall storage potential (per federal state) is written to all storage sites. Cause by these lines: https://github.com/openego/eGon-data/blob/56c4540b1ccc02180b2afa2ff6b61fc089113f3e/src/egon/data/datasets/hydrogen_etrago/storage.py#L196-L198

The selection should be `.loc[rowfilter, "potential"] = ...` instead.

# 4.
Adapt selection of federal state to match the table from InSpEE-DS report

grafik Table taken from https://www.bgr.bund.de/DE/Themen/Nutzung_tieferer_Untergrund_CO2Speicherung/Downloads/InSpeeDS_TP_Bewertungskriterien.html?nn=1547442

Tested allocation to federal states on CI server, should work now.

# 5.
Resolved on 11.11.2021, will be tested in next CI run https://github.com/openego/eGon-data/pull/478#issuecomment-966284345

# 6.
Resolved on 23.11.2021, a0b6a2a8c7da4b3820965cdcbccc5b888f4e532b, d5b5c40d653354e6a0258c715762477295a22b6a, 4b1e66e37e664dbc5727a0a845c0404a5ac08f75

# 7.
Resolved on 23.11.2021 5e4294d

### CODE REVIEW

**Comment by fwitte** [comment]
Run on CI branch did not complete due to #504

**Comment by fwitte** [comment]
After upgrading geopandas manually on the CI server, the data are available. There are still some todos:

- [ ] make sure ids are not duplicated
- [ ] e_nom_max parameter is missing for H2 overground steel tank storage
- [ ] e_nom_max parameter for H2 underground seems excessively large for some locations

**Comment by fwitte** [comment]
Storage potential insertion fixed and tested on CI branch already. Should be working now, will make one more test next week.

**Comment by fwitte** [comment]
The following two datasets have the same name, causing the CI run to fail the task PowertoH2toPower.

https://github.com/openego/eGon-data/blob/a6b4c16b3f6936910e0bd9721394be268ac4ad51/src/egon/data/processing/power_to_h2.py#L16-L23

https://github.com/openego/eGon-data/blob/a6b4c16b3f6936910e0bd9721394be268ac4ad51/src/egon/data/processing/h2_to_ch4.py#L10-L17

Will be renamed accordingly. Is there a possibility to rerun one of the tasks without restarting the CI run completely?

**Comment by fwitte** [comment]
CI run was successful. I also applied some more moving of scripts (#528). Local test run was successful.

**Review by AmeliaNadal — APPROVED** [review]

**Comment by fwitte** [comment]
The tasks inside this PR ran successfully on CI, can we rereview and merge into dev @IlkaCu, @AmeliaNadal?

**Comment by IlkaCu** [comment]
@fwitte: Do you want me to review this PR in addition to @AmeliaNadal? In general we agreed that one approval is sufficient to merge a PR. In case you want the PR to be double-checked, please let me know.

**Comment by fwitte** [comment]
After the discussion today, I found that it was the missing scn_name filter on the bus selection for the voronoi creation causing the gas_areas.create-voronoi task to fail. I open a new issue for this and will create a PR that fixes the issue independently of this PR. We can go ahead and merge here.

**Comment by fwitte** [comment]
Test running the changes regarding #560 locally in the CI. I'll try to merge into the online CI before the weekend run start.

**Pull request merged**
