### PR TITLE
Fix insert-nep-data for pandas==1.3.0

### LINKED ISSUE #322: Task insert-nep-data fails
I ran everything from scratch (on 2 different systems with new px3.8 venv) using current dev and SH region.
The task `insert-nep-data` fails.

Log:
```
[2021-07-09 00:07:40,140] {taskinstance.py:1150} ERROR - 'Schleswig-Holstein'
Traceback (most recent call last):
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Schleswig-Holstein'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nesnoj/git-repos/openego/eGon-data/src/egon/data/importing/nep_input_data/__init__.py", line 341, in insert_data_nep
    insert_capacities_per_federal_state_nep()
  File "/home/nesnoj/git-repos/openego/eGon-data/src/egon/data/importing/nep_input_data/__init__.py", line 173, in insert_capacities_per_federal_state_nep
    data.loc[data.carrier == 'residential_rural_heat_pump', bl] *= 3e-6
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/generic.py", line 3758, in xs
    return self[key]
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/frame.py", line 3455, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/nesnoj/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Schleswig-Holstein'
[2021-07-09 00:07:40,152] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=insert-nep-data, execution_date=20210708T211548, start_date=20210708T220739, end_date=20210708T220740
[2021-07-09 00:07:44,407] {local_task_job.py:102} INFO - Task exited with return code 1
```

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes #322

### CODE REVIEW

**Review by nesnoj — COMMENTED** [review]
I haven't checked yet as I'd like to point out the following:

This probably works for now but I had look into the [pandas whats new v1.3.0](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html#deprecated-dropping-nuisance-columns-in-dataframe-reductions-and-dataframegroupby-operations) it seems like this won't work in the future as it is deprecated. You would have to specify the columns explicitly..
Do you wanna change it accordingly?

**Comment by ClaraBuettner** [comment]
> I haven't checked yet as I'd like to point out the following:
> 
> This probably works for now but I had look into the [pandas whats new v1.3.0](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html#deprecated-dropping-nuisance-columns-in-dataframe-reductions-and-dataframegroupby-operations) it seems like this won't work in the future as it is deprecated. You would have to specify the columns explicitly..
> Do you wanna change it accordingly?

I will try to change it, thank you! 
But since other issues also seem to be related to the pandas release, I also like the idea of setting an upper version limit. These tasks failed, but there might be also other affected tasks which don't fail but create other results.

**Comment by nesnoj** [comment]
Hey @ClaraBuettner, what prevents you to merge this one?

**Comment by ClaraBuettner** [comment]
> Hey @ClaraBuettner, what prevents you to merge this one?

I was waiting for your review.. :)

**Comment by nesnoj** [comment]
> > Hey @ClaraBuettner, what prevents you to merge this one?
> 
> I was waiting for your review.. :)

Oh my god that's so hilarious...sorry

**Review by nesnoj — APPROVED** [review]

**Pull request merged**
