### PR TITLE
Create unique ids on generated tasks

### LINKED ISSUE #985: Having multiple `Dataset`s ending in parallel tasks doesn't work
More specifically, having multiple `Dataset`s ending in parallel tasks doesn't work if those `Dataset`s are in a module below the `egon.data.datasets` package. In that case the code removing the module name prefix from task ids and the code generating the final dataset task which updates the dataset version once all parallel tasks have finished interact in a way that generates non-distinct task ids so that tasks generated later clobber the ones generated earlier. This leads to spurious cycles and other inconsistencies and bugs in the graph.

### PR DESCRIPTION
**Pull request by gnn**
This should fix #985. Would you mind checking whether this actually fixes the parallel task issue you had, @nailend?

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Review by nailend — APPROVED** [review]
Tested it! Works fine

**Comment by nesnoj** [comment]
Is there anything left to be done here?

**Comment by nesnoj** [comment]
> Is there anything left to be done here?

What does your test run say @gnn ?

**Comment by nesnoj** [comment]
> > Is there anything left to be done here?
> 
> What does your test run say @gnn ?

Any updates, @gnn ?

**Pull request merged**
