### PR TITLE
Features/#348 electrical neighbours egon2035

### PR DESCRIPTION
**Pull request by ClaraBuettner**
This branch implements the border crossing lines to central buses per country (for eGon2035). The method use the boundaries to identify cross-border lines, so in test mode all lines crossing the borders of Schleswig-Holstein are connected to one central bus in Germany.
The branch also adds the download of data from TYNDP and uses it to create etrago generators, demands and storage units for eGon2035.

### CODE REVIEW

**Comment by ulfmueller** [comment]
nice, we also get some stuff from dev as an update... As an understanding, the crossborder lines come from osmTGmod and are only relevant for the crossborder lines from and towards Germany, right? So, for the others the p-e-s crossborder lines based on gridkit/entso-e will be taken. 
This, we need for both scenarios. For the crossborder lines from an to Germany, can you do it right away for the eGon100RE scenario as well or shall I do it? If I do it, may be you can give a quick explanation what to do.
For the other country-to-country lines I could implement s.th. to do it also for the NEP scenario. Or do you want to do that?

**Comment by ClaraBuettner** [comment]
> nice, we also get some stuff from dev as an update... As an understanding, the crossborder lines come from osmTGmod and are only relevant for the crossborder lines from and towards Germany, right? So, for the others the p-e-s crossborder lines based on gridkit/entso-e will be taken.

Yes, I only add crossborder lines from/to Germany from osmTGmod and for the lines between neighboring countries data from p-e-s will be used. 

> This, we need for both scenarios. For the crossborder lines from an to Germany, can you do it right away for the eGon100RE scenario as well or shall I do it? If I do it, may be you can give a quick explanation what to do.

I can do this today or tomorrow. 

> For the other country-to-country lines I could implement s.th. to do it also for the NEP scenario. Or do you want to do that?

Could you do this? Otherwise I would some questions...

**Comment by ClaraBuettner** [comment]
I added the crossborder lines (and also buses with v_nom < 380kV and transformers) for eGon100RE in the last commit.

**Comment by ulfmueller** [comment]
Nice!! yes, i will try to add the foreign lines for the NEP scenario today.

**Comment by ulfmueller** [comment]
I added the foreign lines for the eGon2035 scenario in this commit: 20fc5d2f3b51576dd3ed22c6e3cf8064c27b9f80

Besides this, I am fine with the PR - for me it can be merged!

**Comment by ClaraBuettner** [comment]
> I added the foreign lines for the eGon2035 scenario in this commit: [20fc5d2](https://github.com/openego/eGon-data/commit/20fc5d2f3b51576dd3ed22c6e3cf8064c27b9f80)
> 
> Besides this, I am fine with the PR - for me it can be merged!

Thank you! I will merge this now.

**Pull request merged**
