### PR TITLE
Features/#117 import industrial sites

### LINKED ISSUE #117: Import and match data on industrial consumers from external sources
Data from external sources on industrial electricity consumers need to be imported and matched to each other. 

- hotmaps
- s-eenergies
- Thesis DLR-VE

### PR DESCRIPTION
**Pull request by IlkaCu**
Fixes #117.

### CODE REVIEW

**Comment by IlkaCu** [comment]
I updated the hotmaps' merge as I noticed that hotmaps and seenergies using a corresponding siteid which makes the merge easier and fixes the bug which occurred in 'Wahlstedt'

**Comment by IlkaCu** [comment]
@ClaraBuettner: Could you test it for Germany on the server?

**Comment by ClaraBuettner** [comment]
> @ClaraBuettner: Could you test it for Germany on the server?

Yes, I just stared the run and the newly added tasks run successfully. Would you like to see the results? How should I send them to you? I could also give you access to my user on the server as long as you don't have your own one.

**Comment by ClaraBuettner** [comment]
I removed the function calls at the end of  `src/egon/data/importing/industrial_sites/__init__.py` because they broke the tox. and GitHub tests (and also the dag when the tasks weren't executed before). I guess you only used them for testing.
If the results are fine, this can be merged.

**Review by ClaraBuettner — APPROVED** [review]

**Comment by IlkaCu** [comment]
@ClaraBuettner: Could you test the code once again on your computer before I merge it into our dev branch? Thx

**Review by ClaraBuettner — APPROVED** [review]
I tested the branch again on the server, the additional tasks run successfully. (846 industrial sites are identified in Germany).

**Pull request merged**
