### PR TITLE
Features/#378 update industrial demand

### LINKED ISSUE #378: Filter industrial landuse areas from osm
The industrial demands are currently distributed to all osm areas which are tagged with `landuse = 'industrial' `. 
This also includes areas that do not have an industrial energy demand (e.g. Stadtwerke, Gewerbegebiete or solar parks). 
Th identify possible locations for industrial CHP I filtered the industrial areas, this might be also used to filter the areas which get an industrial demand: https://github.com/openego/eGon-data/blob/d062dd149583c74240fda28e9e746d69b735f6b8/src/egon/data/datasets/chp/small_chp.py#L297-L311

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Closes #378

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
I tried to run this branch but I run into this error:

```
2021-08-13 15:14:24,367] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.industry.industrial-demand-distr 2021-08-13T12:14:12.936272+00:00 [running]> on host clara-LIFEBOOK-U749
[2021-08-13 15:14:25,259] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "demand.egon_industrial_sites" does not exist
LINE 7: ...   (SELECT ST_UNION(ST_Transform(geom,3035)) FROM demand.ego...
                                                             ^

[SQL: SELECT gid, area_ha, geom FROM
                openstreetmap.
                osm_landuse
                WHERE sector = 3
                AND NOT ST_Intersects(
                    geom,
                    (SELECT ST_UNION(ST_Transform(geom,3035)) FROM demand.egon_industrial_sites))
                AND name NOT LIKE '%%kraftwerk%%'
                AND name NOT LIKE '%%Stadtwerke%%'
                AND name NOT LIKE '%%Müllverbrennung%%'
                AND name NOT LIKE '%%Müllverwertung%%'
                AND name NOT LIKE '%%Abfall%%'
                AND name NOT LIKE '%%Kraftwerk%%'
                AND name NOT LIKE '%%Wertstoff%%'
                AND name NOT LIKE '%%olarpark%%'
                AND name NOT LIKE '%%Gewerbegebiet%%'
                AND name NOT LIKE '%%Gewerbepark%%'
                AND name NOT LIKE '%%heizwerk%%'
                AND name NOT LIKE '%%Heizwerk%%'
                AND name NOT LIKE '%%Kläranlage%%'
                AND name NOT LIKE '%%Klärwerk%%'
                AND name NOT LIKE '%%Biogasanlage%%'
                AND name NOT LIKE '%%Wasserwerk%%'
                AND name NOT LIKE '%%Recyclinghof%%'
                AND name NOT LIKE '%%Recyclingpark%%']
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/home/clara/new-test-egon-data/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/clara/new-test-egon-data/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "demand.egon_industrial_sites" does not exist
LINE 7: ...   (SELECT ST_UNION(ST_Transform(geom,3035)) FROM demand.ego...


```
Somehow the tables are not created. I will try to fix this.

**Comment by ClaraBuettner** [comment]
> I tried to run this branch but I run into this error:
> 
> ```
> 2021-08-13 15:14:24,367] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.industry.industrial-demand-distr 2021-08-13T12:14:12.936272+00:00 [running]> on host clara-LIFEBOOK-U749
> [2021-08-13 15:14:25,259] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "demand.egon_industrial_sites" does not exist
> LINE 7: ...   (SELECT ST_UNION(ST_Transform(geom,3035)) FROM demand.ego...
>                                                              ^
> 
> [SQL: SELECT gid, area_ha, geom FROM
>                 openstreetmap.
>                 osm_landuse
>                 WHERE sector = 3
>                 AND NOT ST_Intersects(
>                     geom,
>                     (SELECT ST_UNION(ST_Transform(geom,3035)) FROM demand.egon_industrial_sites))
>                 AND name NOT LIKE '%%kraftwerk%%'
>                 AND name NOT LIKE '%%Stadtwerke%%'
>                 AND name NOT LIKE '%%Müllverbrennung%%'
>                 AND name NOT LIKE '%%Müllverwertung%%'
>                 AND name NOT LIKE '%%Abfall%%'
>                 AND name NOT LIKE '%%Kraftwerk%%'
>                 AND name NOT LIKE '%%Wertstoff%%'
>                 AND name NOT LIKE '%%olarpark%%'
>                 AND name NOT LIKE '%%Gewerbegebiet%%'
>                 AND name NOT LIKE '%%Gewerbepark%%'
>                 AND name NOT LIKE '%%heizwerk%%'
>                 AND name NOT LIKE '%%Heizwerk%%'
>                 AND name NOT LIKE '%%Kläranlage%%'
>                 AND name NOT LIKE '%%Klärwerk%%'
>                 AND name NOT LIKE '%%Biogasanlage%%'
>                 AND name NOT LIKE '%%Wasserwerk%%'
>                 AND name NOT LIKE '%%Recyclinghof%%'
>                 AND name NOT LIKE '%%Recyclingpark%%']
> (Background on this error at: http://sqlalche.me/e/13/f405)
> Traceback (most recent call last):
>   File "/home/clara/new-test-egon-data/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
>     cursor, statement, parameters, context
>   File "/home/clara/new-test-egon-data/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
>     cursor.execute(statement, parameters)
> psycopg2.errors.UndefinedTable: relation "demand.egon_industrial_sites" does not exist
> LINE 7: ...   (SELECT ST_UNION(ST_Transform(geom,3035)) FROM demand.ego...
> ```
> 
> Somehow the tables are not created. I will try to fix this.

I pulled again from this branch, and everything was working, sorry for the confusion.

**Comment by IlkaCu** [comment]
Meanwhile I already noticed this problem and increased the version number here: 9bd7968c582dcbca8e2e686584ed2b1851b9dceb

**Review by IlkaCu — APPROVED** [review]

**Comment by IlkaCu** [comment]
If you agree to merge this branch into dev, please do so. In my case the industry parts finished successfully

**Pull request merged**
