### PR TITLE
Features/#392 include powerplants

### LINKED ISSUE #392: Include missing power plants
The following technologies need to be integrated into the egon-data workflow

- [ ] pumped hydro 
- [ ] gas
- [ ] oil
- [ ] other renewable
- [ ] other conventional

Relevant input tables are `supply.egn_scenario_capacities` and `supply.nep_2021_conv_powerplant` as well as the data retrieved from MaStR (e.g. bnetza_mastr_storage_cleaned.csv)

### PR DESCRIPTION
**Pull request by IlkaCu**
Closes #392 by allocating and integrating conventional non CHP power plants into the power plants table. 
Branch still needs to be tested for Germany on the CI branch

### CODE REVIEW

**Comment by IlkaCu** [comment]
This feature got tested on the CI branch and the tasks were run successfully, but no data for carrier 'gas' and 'oil' git written to the database. This needs to be solved.

**Review by ClaraBuettner — CHANGES_REQUESTED** [review]
I run this branch in testmode and it failed: 
```
[2021-09-30 13:54:25,452] {logging_mixin.py:120} INFO - WARNING: No data returned by statement: 
 
        SELECT bnetza_id, name, carrier, capacity, postcode, city,
        federal_state, c2035_capacity
        FROM supply.egon_nep_2021_conventional_powerplants
        WHERE carrier = 'oil'
        AND chp = 'Nein'
        AND c2035_chp = 'Nein'
        AND c2035_capacity > 0
        AND postcode != 'None';
[2021-09-30 13:54:26,083] {taskinstance.py:1150} ERROR - Cannot transform naive geometries.  Please set a crs on the object first.
Traceback (most recent call last):

```
I think this happens because there are no oil power plants in Schleswig-Holstein.

**Comment by IlkaCu** [comment]
I added an if...else and print statement to avoid problems with empty data frames imported from our NEP tables.

**Comment by ClaraBuettner** [comment]
There were some issues in the CHP extension, but after I merged the `dev` branch into this feature-branch it was running successful.

**Comment by ClaraBuettner** [comment]
The task `power_plants.allocate-conventional-non-chp-power-plants` failed on the CI-branch:
```
Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/power_plants/__init__.py", line 618, in allocate_conventional_non_chp_power_plants
    mastr = select_no_chp_combustion_mastr(carrier)
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/datasets/power_plants/conventional.py", line 72, in select_no_chp_combustion_mastr
    mastr = db.select_geodataframe(
  File "/home/egondata/git-repos/friday-evening-weekend-run/code/src/egon/data/db.py", line 205, in select_geodataframe
    gdf = gpd.read_postgis(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1247, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/geopandas/geoseries.py", line 1028, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/geopandas/array.py", line 780, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
```
The used table for non chp plants is filled in the CHP-data set, but this is not a dependency of the PowerPlant-Dataset. I think adding the dependency should solve the problem.

**Pull request merged**
