### PR TITLE
Allow working without Docker

### PR DESCRIPTION
**Pull request by gnn**
This is the PR for issue #64. While the specifics of the implementation, like configuration file location and format or the command line switches, could potentially change, this should at least pose a viable solution.

### CODE REVIEW

**Comment by gnn** [comment]
Specifying your own configuration for the database is probably most easily done using command line switches to `egon-data`. For example if you want to run `egon-data serve` with your own database configuration, you would do something like:

```
egon-data \
  --database=DATABASE-NAME \
  --database-user=USERNAME \
  --database-password=PW \
  --database-host=HOST \
  --database-port=PORT \
  serve
```

where you replace all the words in capital letters with the values necessary to connect to your database. You only need to do this the first time though, because when you do this, `egon-data` will create the "local-database.yaml" file containing the supplied values, in the current directory. Every subsequent `egon-data` run will continue to use the values in this file as long as it's there.

**Comment by gplssm** [comment]
I tried to start the webserver with `egon-data serve`. 

```
(eGon-data-new-editable) guido@RLI-NB-49:~/git/eGon-data/src/egon/data$ egon-data serve
/home/guido/miniconda3/envs/eGon-data-new-editable/lib/python3.7/site-packages/airflow/configuration.py:761: DeprecationWarning: You have two airflow.cfg files: /home/guido/airflow/airflow.cfg and /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg, and you should remove the other file
  category=DeprecationWarning,
DB: sqlite:////home/guido/git/eGon-data/src/egon/data/airflow/airflow.db
[2021-01-11 17:16:57,740] {db.py:378} INFO - Creating tables
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
WARNI [airflow.models.crypto] cryptography not found - values will not be stored encrypted.
Done.
/home/guido/miniconda3/envs/eGon-data-new-editable/lib/python3.7/site-packages/airflow/configuration.py:761: DeprecationWarning: You have two airflow.cfg files: /home/guido/airflow/airflow.cfg and /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg, and you should remove the other file
  category=DeprecationWarning,
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-01-11 17:16:59,304] {__init__.py:50} INFO - Using executor SequentialExecutor
[2021-01-11 17:16:59,304] {dagbag.py:417} INFO - Filling up the DagBag from /home/guido/git/eGon-data/src/egon/data/airflow/dags
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
=================================================================            

Error: No module named 'airflow.www'
```

The airflow gui is not reachable.

I assumed without using the newly introduced flags, it should take defaults values for the database connection. Namely the same ones as prior to this feature. Is this a wrong assumption?

I get the same results using 
```
egon-data --database egon-data --database-user egon --database-password data --database-port 54321 --database-host localhost serve
```

**Comment by gplssm** [comment]
> I tried to start the webserver with `egon-data serve`.
> 
> ```
> (eGon-data-new-editable) guido@RLI-NB-49:~/git/eGon-data/src/egon/data$ egon-data serve
> /home/guido/miniconda3/envs/eGon-data-new-editable/lib/python3.7/site-packages/airflow/configuration.py:761: DeprecationWarning: You have two airflow.cfg files: /home/guido/airflow/airflow.cfg and /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg, and you should remove the other file
>   category=DeprecationWarning,
> DB: sqlite:////home/guido/git/eGon-data/src/egon/data/airflow/airflow.db
> [2021-01-11 17:16:57,740] {db.py:378} INFO - Creating tables
> INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
> INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> WARNI [airflow.models.crypto] cryptography not found - values will not be stored encrypted.
> Done.
> /home/guido/miniconda3/envs/eGon-data-new-editable/lib/python3.7/site-packages/airflow/configuration.py:761: DeprecationWarning: You have two airflow.cfg files: /home/guido/airflow/airflow.cfg and /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /home/guido/git/eGon-data/src/egon/data/airflow/airflow.cfg, and you should remove the other file
>   category=DeprecationWarning,
>   ____________       _____________
>  ____    |__( )_________  __/__  /________      __
> ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
> ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
>  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
> [2021-01-11 17:16:59,304] {__init__.py:50} INFO - Using executor SequentialExecutor
> [2021-01-11 17:16:59,304] {dagbag.py:417} INFO - Filling up the DagBag from /home/guido/git/eGon-data/src/egon/data/airflow/dags
> Running the Gunicorn Server with:
> Workers: 4 sync
> Host: 0.0.0.0:8080
> Timeout: 120
> Logfiles: - -
> =================================================================            
> 
> Error: No module named 'airflow.www'
> ```
> 
> The airflow gui is not reachable.
> 
> I assumed without using the newly introduced flags, it should take defaults values for the database connection. Namely the same ones as prior to this feature. Is this a wrong assumption?
> 
> I get the same results using
> 
> ```
> egon-data --database egon-data --database-user egon --database-password data --database-port 54321 --database-host localhost serve
> ```

Can be resolved with a re-install.

**Review by wheitkoetter — APPROVED** [review]
I am not an expert on this topic, but from my point of view it looks okay and I approve the changes. Thanks!

**Review by AmeliaNadal — APPROVED** [review]

**Pull request merged**
