### PR TITLE
Fix DSM time series

### LINKED ISSUE #1088: Faulty DSM time series
The DSM time series appear implausible at the moment.

- [x] `p_max_pu` and `p_min_pu` are not clipped at 0
- [ ] ~~`p_max_pu` and `p_min_pu` are sometimes larger than `p_set`~~ (after a discussion with @KathiEsterl and @ClaraBuettner this seems to be justifiable)
- [x] The wrong `p_set` time series is saved

### PR DESCRIPTION
**Pull request by khelfen**
Fixes #1088 .

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by khelfen** [comment]
@ClaraBuettner / @IlkaCu this PR is completed from my side. Is there any CI run planned? In which CI branch should I merge those changes for testing?

**Comment by IlkaCu** [comment]
You can use CI branch `continuous-integration/run-everything-2022-11-10`. But we didn't schedule the new CI run yet.

**Comment by khelfen** [comment]
@KathiEsterl maybe you could already review this PR?

**Comment by KathiEsterl** [comment]
Do you think it is necessary to run the code and check the results again? 
I would suggest to approve it, although I "only" looked at the changes in the code one more time and checked the code together with you yesterday. I think for those changes this is sufficient.

**Review by KathiEsterl — APPROVED** [review]

**Comment by KathiEsterl** [comment]
It has been running on CI meanwhile, right? How is it about the tolerances? If everything is fine, we can merge it to dev now, I guess.

**Pull request merged**
