### PR TITLE
Identify medium-voltage grid districts

### LINKED ISSUE #10: Review and move griddistrict scripts
Scripts from section 'Griddistrict' need to be reviewed, adjusted and moved to the new repo: 

- [x] [ego_dp_mv_griddistrict.sql](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/dataprocessing/sql_snippets/ego_dp_mv_griddistrict.sql)
  - [x] Count number of substations per municipality and store in table
  - [x] Apply use voronoi cells for municipalities of type 2 (with > 1 substations) and apply cutting
  - [x] Merge cut polygons with next neighboring municipality that has a substation
  - [x] Handle type 3 municipalities (those without a substation)
- [ ] [ego_dp_substation_id_to_generator.sql](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/dataprocessing/sql_snippets/ego_dp_substation_id_to_generator.sql)

### PR DESCRIPTION
**Pull request by gplssm**
This pull request introduces code for identifying mediu-voltage grid districts based on municipality boundaries, HV-MV substations and voronoi polygons around these. Please see documentation along code for further details.

I couldn't perform a final check if everything runs smoothly in the pipeline because creation of voronoi failed, see #221.

Did not work on [ego_dp_substation_id_to_generator.sql](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/dataprocessing/sql_snippets/ego_dp_substation_id_to_generator.sql) at all, because I assumed power plant data isn't ready yet.

Fixes #10.

### CODE REVIEW

**Comment by gplssm** [comment]
I was able to run the entire pipeline successfully. The resulting MV grid districts look like this

MV_grid_districts

**Review by IlkaCu — COMMENTED** [review]
I was able to run the workflow without any error or warning. 👍
Unfortunately some of the results seem a bit weird to me. 
In the example below it seems that the marked municipality should be assigned to substation B, as it is located very closely, but it is part of A's grid district.
Auffaelligkeit_mvgriddistrict

@gplssm: Any ideas why this happens?

**Comment by gplssm** [comment]
Interesting! I compared the results on your side with mine. Therefore, I assumed A = subst_id 146 and B = subst_id 150.

In the plot I've posted above, the polygon highlighted in yellow, is assigned to substation 150, as requested by you. Now, I wonder if the results are reproducible...!?

There's one further explanation that might be relevant: the assignment to substations is determined by proximity of polygons, not proximity of (to-be-assigned-)polygons to substations. This might lead to the weird looking result, that a "foreign" substation is very close to the border of another grid district.

I gonna re-run the workflow and see if I can reproduce the results.

**Comment by gplssm** [comment]
I tried to reproduce my/your results and I got the same as shown initially. Hence, I couldn't reproduce your results.

grafik

**Comment by IlkaCu** [comment]
Interesting. Then I will try to rerun the workflow and see what happens.

**Comment by gplssm** [comment]
With 3a30a39 MV grid district creation returns reproducible results. It was verified using [this comparison script](https://gist.github.com/gplssm/760d0b98264d0660832b9174bf2ff61e) to compare results of 7 independent runs.

The shapes of the resulting MV grid districts are quite ok. The "Niebül problem" (Niebül is connected to substation 141 instead of 145) occurs reproducible now. There are some similar cases where a substation in a non-voronoi-cut polygon is quite close to the grid district boundary.

MV_grid_districts_reproducible

I'm quite ok with the results and I would not like to spent more time here.

@IlkaCu what's your opinion?

**Comment by gplssm** [comment]
The Niebül problem was discussed again and it was decided to resolve it later (see #231 ). For now, we take the current implementation.

**Comment by gplssm** [comment]
> The Niebüll problem was discussed again and it was decided to resolve it later (see #231 ). For now, we take the current implementation.

I decided to give it one quick try. Here's the result:


MV_grid_districts_centroid_sorting

MV_grid_districts_centroid_sorting_Niebüll

@IlkaCu if you could quickly take a look on the above picture and approve the PR, I gonna merge it.

**Review by IlkaCu — APPROVED** [review]
Looks much better! Thanks for the quick implementation. 
I didn't test the workflow again on my computer. If you want me to do that - let me know.

**Comment by gplssm** [comment]
> Looks much better! Thanks for the quick implementation.
> I didn't test the workflow again on my computer. If you want me to do that - let me know.

Thanks! Another run on your computer is not necessary. Didn't changed things fundamentally and a tested again after merging dev into this feature branch for resolving conflicts. So I gonna merge now :)

**Pull request merged**
