### PR TITLE
Features/#866 data bundle v10

### LINKED ISSUE #815: Timeseries for foreign generators have only 2920 values
Due to the 3-hourly-resolution of the current pypsa-eur-sec run, the copied timeseries for foreign generators have only 2920 entries.
As long as there is no hourly data from pypsa-eur-sec, the data should be copied for the in between hours before writing into the eTraGo tables.

### LINKED ISSUE #866: Zenodo data bundle v0.9 - 2nd attempt
Update of [data bundle](https://zenodo.org/record/4896526).

To be added (tick if added on NC including description):
- [x] updated p-e-s results
- [x] updated data from Netzentwicklungsplan (include batteries) 

Feel free to add further datasets until Thursday noon.

### PR DESCRIPTION
**Pull request by IlkaCu**
Fixes #866 .
Fixes #815 

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by nesnoj** [comment]
@IlkaCu I just ran SH (latest CI) and `scenario_capacities.eGon100-capacities` says `FileNotFoundError: [Errno 2] No such file or directory: 'data_bundle_egon_data/pypsa_eur_sec/2022-05-04-egondata-integration/csvs/nodal_capacities.csv'`
Seems that there are version conflicts with the data bundle (I have `2022-07-26-egondata-integration` in my instance..).

**Comment by nesnoj** [comment]
> @IlkaCu I just ran SH (latest CI) and `scenario_capacities.eGon100-capacities` says `FileNotFoundError: [Errno 2] No such file or directory: 'data_bundle_egon_data/pypsa_eur_sec/2022-05-04-egondata-integration/csvs/nodal_capacities.csv'` Seems that there are version conflicts with the data bundle (I have `2022-07-26-egondata-integration` in my instance..).

Some problem with `gas_neighbours.tyndp-gas-demand`

**Comment by nesnoj** [comment]
Thanks for the fix. Not sure if this is related to the bundle but now in the task `scenario_capacities.eGon100-capacities` I'm getting
```
[2022-08-26 10:06:58,780] {taskinstance.py:1150} ERROR - 'residential_rural_resistive_heater'
Traceback (most recent call last):
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3081, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'residential_rural_resistive_heater'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data-sh/code/src/egon/data/datasets/scenario_capacities.py", line 668, in eGon100_capacities
    df.p_nom[f"residential_{merge_carrier}"]
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/core/series.py", line 853, in __getitem__
    return self._get_value(key)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/core/series.py", line 961, in _get_value
    loc = self.index.get_loc(label)
  File "/storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3083, in get_loc
    raise KeyError(key) from err
KeyError: 'residential_rural_resistive_heater'
```

**Comment by nesnoj** [comment]
Thanks for the fix in 05f33cb - I'm close on your heels ;).
Now in task `chp.insert-chp-egon2035`:
```
[2022-08-26 12:03:27,725] {logging_mixin.py:120} INFO - No information about MaStR location available. All voltage levels are assigned using threshold values.
[2022-08-26 12:03:27,846] {logging_mixin.py:120} INFO - 704.9 MW matched
[2022-08-26 12:03:27,846] {logging_mixin.py:120} INFO - 0.0 MW not matched
[2022-08-26 12:03:28,599] {logging_mixin.py:120} INFO - WARNING: No data returned by statement: 
 
        SELECT bus_id, geom FROM grid.egon_gas_voronoi
        WHERE scn_name = 'eGon2035' AND carrier = 'CH4';
[2022-08-26 12:03:28,600] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh/code/src/egon/data/db.py:382: UserWarning: CRS mismatch between the CRS of left geometries and the CRS of right geometries.
Use `to_crs()` to reproject one of the input geometries to match the CRS of the other.

Left CRS: EPSG:4326
Right CRS: None

  res = gpd.sjoin(dataframe, voronoi)
[2022-08-26 12:03:30,069] {logging_mixin.py:120} WARNING - /storage/eGon-data-sh/venv/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
[2022-08-26 12:03:30,167] {taskinstance.py:1150} ERROR - (psycopg2.errors.NumericValueOutOfRange) integer out of range
```

**Review by ClaraBuettner — APPROVED** [review]

**Pull request merged**
