### PR TITLE
Fixes/#585 heat demand profiles at border

### LINKED ISSUE #585: Missing heat demand profiles for zensus cells close to German border
Some zensus cells close to the German border are not intersecting with the climate_zone shape file. These cells get lost in these lines: 

https://github.com/openego/eGon-data/blob/0730acfae19def9381f184b28f3304c5f7c0be3c/src/egon/data/datasets/heat_demand_timeseries/HTS.py#L629-L631

Can be fixed by using gpd.sjoin_nearest() instead of gpd.sjoin()

Waits for #558

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes #585 . 

Depends on #558 

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
This branch was tested on CI. @nailend query in #558 returns no zensus cells with households but without heat profiles. 
@nailend and @nesnoj could one of you review this PR?

**Comment by nesnoj** [comment]
Hmm, when I run the mentioned query (CI run on Flensburg server) I'm getting

image

`heat_buildings` is expected to be filled, right?

**Comment by ClaraBuettner** [comment]
> Hmm, when I run the mentioned query (CI run on Flensburg server) I'm getting
> 
> image
> 
> `heat_buildings` is expected to be filled, right?

Sorry for the confusion, there are different queries in #558
Did you run the query in https://github.com/openego/eGon-data/pull/558#pullrequestreview-829567250 or the one in https://github.com/openego/eGon-data/pull/558#issuecomment-996705984?
The first one also includes cells which have CTS heat demand but no heat demand for households. When there is no household heat demand in peta, we don't select heat demand profiles.

**Review by nesnoj — APPROVED** [review]
Thanks for the clarification, seems this is good to go now..

**Pull request merged**
