### PR TITLE
Features/#868 create wind offshore generators for the eGon100RE scenario

### PR DESCRIPTION
**Pull request by CarlosEpia**
Add feature described in #868.

## Before merging into `dev`-branch, please make sure that

- [X] the `CHANGELOG.rst` was updated.
- [X] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Review by IlkaCu — COMMENTED** [review]
Version number should be increased

**Review by IlkaCu — APPROVED** [review]

**Comment by CarlosEpia** [comment]
The wind offshore generators for the scenario eGon100RE look ok and the total installed capacity matches the value in the table egon_scenario_capacities

**Comment by IlkaCu** [comment]
@CarlosEpia: Here it says that the branch has unmerged commits. How did that happen?

**Comment by CarlosEpia** [comment]
I can't really say why this happened, but I reopened and merged again this PR. Now the warning is gone.

**Pull request merged**
