### PR TITLE
Use random seed from CLI parameters for CHP and society prognosis

### LINKED ISSUE #351: Random seed for reproducibility
The random module is used in several tasks. To make a further step towards reproducibility, a predefined seed should be used.
In a linear program it's sufficient to set the seed only once according to [this SO post](https://stackoverflow.com/a/11527011). But as we're running multiple tasks in parallel, the order of the drawings is not deterministic, right?

So what about defining a seed centrally in egon-data and set it in every affected script, does this sound like a good solution to you? @gnn What would be a good place to store the seed? I couldn't find an appropriate file, maybe datasets.yml but this is not the actual intention of the file.. (apart from the fact that we wanted to switch to a more decentralized concept here)

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Closes #351 

This branch uses the random seed from the configuration file in the CHP and society prognosis function.

### CODE REVIEW

**Review by nesnoj — COMMENTED** [review]
I assume u want me to review despite the fact that this PR is still in draft mode?!

Some remarks:
- is there a reason u didn't bump the CHP version no?
- apart from the seed stuff: the small CHP stuff currently seems not to be used? At least I could not find a call of the function [`extension()`](https://github.com/openego/eGon-data/blob/1ae914887cbfefdab6863fea350f0a76bc548823/src/egon/data/datasets/chp/__init__.py#L217) except for an [commented out](https://github.com/openego/eGon-data/blob/1ae914887cbfefdab6863fea350f0a76bc548823/src/egon/data/datasets/chp/__init__.py#L55) one... ?

**Comment by ClaraBuettner** [comment]
> I assume u want me to review despite the fact that this PR is still in draft mode?!
> 
I'm sorry but I'm still a bit confused by the CI-branch. I wanted to mark this as ready for review when it is tested also for Germany. 

> Some remarks:
> 
>     * is there a reason u didn't bump the CHP version no?
> 
>     * apart from the seed stuff: the small CHP stuff currently seems not to be used? At least I could not find a call of the function [`extension()`](https://github.com/openego/eGon-data/blob/1ae914887cbfefdab6863fea350f0a76bc548823/src/egon/data/datasets/chp/__init__.py#L217) except for an [commented out](https://github.com/openego/eGon-data/blob/1ae914887cbfefdab6863fea350f0a76bc548823/src/egon/data/datasets/chp/__init__.py#L55) one... ?

I did not update the version number of CHP because the small chp extension which was updated is currently not used. I'm still working on it and will 'activate' it when I'm done. 
I already added the random seed for the not-used extension of small chp to not forget it later on.

**Review by nesnoj — APPROVED** [review]
:+1:

**Comment by ClaraBuettner** [comment]
This feature was tested successfully on CI-branch for Germany, so I merge this into dev.

**Pull request merged**
