### PR TITLE
Assign hh demand profiles to buildings

### LINKED ISSUE #435: Assign HH demand profiles to buildings
Each building in table `openstreetmap.osm_buildings_filtered` (created in #262/#430, not available in dev yet) needs to get assigned profiles from table `demand.egon_household_electricity_profile_in_census_cell`.

Notes
- [x] New table `demand.egon_household_electricity_profile_in_building` with `osm_id` and `building_profile_ids` (same format as in `demand.egon_household_electricity_profile_in_census_cell`'s `cell_profile_ids`)
- [x] For the mapping of buildings to zensus cells, you can use table `boundaries.egon_map_zensus_buildings_filtered` (currently only available in branch `features/#262-preprocess-osm-buildings-amenities` #430 as well as in the weekend branch)
- [x] Distribute randomly, it is more important that every building gets a profile than one gets multiple profiles
- [ ] (nice-to-have: can we easily consider the buildings' area?)
- [x] If no. of profiles < no. of buildings: ok for now, some buildings don't get a profile assigned as not all buildings are residential
- [x] If no. of profiles > no. of buildings: ok
- [ ] <s> If no. of profiles >> no. of buildings: we have to create some virtual buildings. To start, check with column `building_count` in table `society.egon_destatis_zensus_apartment_building_population_per_ha` if we have at least zensus data on the no. of buildings. We have to discuss further steps here..</s>
- [ ] Challenge: how to cope with cells without profiles? #431
- [x] Please integrate into hh demand task
- [x] Add peak load to building by summing up the profiles and use max

### PR DESCRIPTION
**Pull request by nailend**
close #435 

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by nesnoj** [comment]
2 quick notes:
- the scripts contain some old functions (commented out), are they still needed?
- the SQL script can be removed, right?

**Comment by nesnoj** [comment]
Prior to a thorough check, could you remove the merge conflicts, please?

**Comment by nailend** [comment]
> Prior to a thorough check, could you remove the merge conflicts, please?

already done

**Comment by nesnoj** [comment]
> Prior to a thorough check, could you remove the merge conflicts, please?

Oh sorry, did not refresh..
Will check asap

**Review by nesnoj — APPROVED** [review]

**Pull request merged**
