### PR TITLE
Fix issues with chp extension 

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes # . 

## Before merging into `dev`-branch, please make sure that

- [ ] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [ ] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend-v2`- branch.
- [ ] the workflow is running successful in `test mode`.
- [ ] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Review by IlkaCu — APPROVED** [review]

**Comment by nesnoj** [comment]
Does this work for you? E.g. for `chp.extension-BW` (and 5 others) I'm still getting (weekend v2):
```
[2022-02-24 11:36:05,952] {taskinstance.py:901} INFO - Executing <Task(Chp (versioned)): chp.extension-BW> on 2022-02-23T11:08:11.084089+00:00
[2022-02-24 11:36:05,961] {standard_task_runner.py:54} INFO - Started process 3437757 to run task
[2022-02-24 11:36:05,991] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'chp.extension-BW', '2022-02-23T11:08:11.084089+00:00', '--job_id', '586', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpy053fkes']
[2022-02-24 11:36:05,991] {standard_task_runner.py:78} INFO - Job 586: Subtask chp.extension-BW
[2022-02-24 11:36:06,102] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.chp.extension-BW 2022-02-23T11:08:11.084089+00:00 [running]> on host ws-02lin.rl-institut.local
[2022-02-24 11:36:07,422] {logging_mixin.py:120} INFO - Target capacity in BadenWuerttemberg: 1400.0
[2022-02-24 11:36:07,423] {logging_mixin.py:120} INFO - Existing capacity in BadenWuerttemberg: 563.18724
[2022-02-24 11:36:07,423] {logging_mixin.py:120} INFO - Distributing 836.81276 MW_el in BadenWuerttemberg
[2022-02-24 11:36:07,424] {logging_mixin.py:120} INFO - Distributing 267.39119596975297 MW_el to district heating
[2022-02-24 11:36:15,282] {taskinstance.py:1150} ERROR - The GeoSeries already has a CRS which is not equal to the passed CRS. Specify 'allow_override=True' to allow replacing the existing CRS without doing any transformation. If you actually want to transform the geometries, use 'GeoSeries.to_crs' instead.
Traceback (most recent call last):
  File "/storage/eGon-data2/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data2/code/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data2/code/src/egon/data/datasets/chp/__init__.py", line 351, in extension_BW
    extension_per_federal_state("BadenWuerttemberg", EgonChp)
  File "/storage/eGon-data2/code/src/egon/data/datasets/chp/small_chp.py", line 590, in extension_per_federal_state
    not_distributed_capacity_dh = extension_district_heating(
  File "/storage/eGon-data2/code/src/egon/data/datasets/chp/small_chp.py", line 379, in extension_district_heating
    dh_areas = dh_areas.append(
  File "/storage/eGon-data2/venv/lib/python3.8/site-packages/geopandas/geodataframe.py", line 1190, in set_crs
    df.geometry = df.geometry.set_crs(
  File "/storage/eGon-data2/venv/lib/python3.8/site-packages/geopandas/geoseries.py", line 1030, in set_crs
    raise ValueError(
ValueError: The GeoSeries already has a CRS which is not equal to the passed CRS. Specify 'allow_override=True' to allow replacing the existing CRS without doing any transformation. If you actually want to transform the geometries, use 'GeoSeries.to_crs' instead.
[2022-02-24 11:36:15,426] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=chp.extension-BW, execution_date=20220223T110811, start_date=20220224T103605, end_date=20220224T103615
[2022-02-24 11:36:20,770] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by ClaraBuettner** [comment]
> Does this work for you? E.g. for `chp.extension-BW` (and 5 others) I'm still getting (weekend v2):

Before this merge, only `chp.extension-HH` failed but the others were working... I will have a look at that. Did it also failed for Schleswig Holstein?

**Comment by nesnoj** [comment]
> > Does this work for you? E.g. for `chp.extension-BW` (and 5 others) I'm still getting (weekend v2):
> 
> Before this merge, only `chp.extension-HH` failed but the others were working... I will have a look at that. Did it also failed for Schleswig Holstein?

If you mean test region run, I haven't tried this, I'm running DE.
If you mean the task `chp.extension-SH`, yes (same error as above, last time it ran successfully was on 21.02., started to fail on 23.02.):

grafik

**Comment by nesnoj** [comment]
Ah, now the tasks are running for longer than just a couple of seconds, looks better.... getting the first :green_square: :smiley: .
Apparently, the CI did not contain your fixing commits yesterday.

**Pull request merged**
