### PR TITLE
Insert carriers into eTraGo table

### LINKED ISSUE #551: Insert carriers into grid.egon_etrago_carrier
The table `grid.egon_etrago_carrier` is not filled yet, which results in errors in some of eTraGo's plotting functions. 
At least the names of carriers have to be inserted into the table.

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes #551  . 

@fwitte: Could you add the missing carriers from the gas sector? 

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by fwitte** [comment]
I will look into it after I debugging the bus related workflows.

**Review by fwitte — APPROVED** [review]

**Comment by fwitte** [comment]
I added a method that checks if the eTraGo tables use any carriers, that are not defined in the carriers table. We could add this task at the very end of the pipeline or just run the method after the CI run manually.

**Comment by ClaraBuettner** [comment]
> I added a method that checks if the eTraGo tables use any carriers, that are not defined in the carriers table. We could add this task at the very end of the pipeline or just run the method after the CI run manually. What do you think @ClaraBuettner?

Thank you! We want to add a task to checks the final input data for etrago and include this function.

**Comment by fwitte** [comment]
Everything looks fine from our side here!

**Pull request merged**
