### PR TITLE
Features/#259 dsm cts

### LINKED ISSUE #259: DSM for CTS and Industry
Demand Side Management for CTS and Industry:

CTS: 
Cooling, Ventilation, AC per area

Industry: 
1) Ventilation & Cooling per osm-area 
2) Ventilation for industrial sites of WZ 23 
3) process related potentials for special applications of industrial sites

### PR DESCRIPTION
**Pull request by KathiEsterl**
Implementation of DSM for CTS and industry sector in data model to be integrated in eTraGo: closes #259

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
This branch also includes changes from other feature branches which are not in `dev` branch yet because you merged the continuous-integration branch into this branch in 632f3ebae15462c3b7308f45128cfdcf6f82ccdf . 
When we merge this branch into `dev`, all other feature-branches from the CI-branch would be also merged into `dev`. But they need to be tested and merged individually. 
Could you try to revert the commit mentioned above?

**Comment by KathiEsterl** [comment]
> This branch also includes changes from other feature branches which are not in `dev` branch yet because you merged the continuous-integration branch into this branch in [632f3eb](https://github.com/openego/eGon-data/commit/632f3ebae15462c3b7308f45128cfdcf6f82ccdf) . When we merge this branch into `dev`, all other feature-branches from the CI-branch would be also merged into `dev`. But they need to be tested and merged individually. Could you try to revert the commit mentioned above?

It should be fine now, I guess?

**Comment by ClaraBuettner** [comment]
> It should be fine now, I guess?

One empty line is deleted in `src/egon/data/datasets/industrial_sites/__init__.py`. It will not change the results, but if it's not that complicated, I would change it. 

Did you already tested it again after reverting and merging? Otherwise I will run it again in test-mode.

**Comment by KathiEsterl** [comment]
> > It should be fine now, I guess?
> 
> One empty line is deleted in `src/egon/data/datasets/industrial_sites/__init__.py`. It will not change the results, but if it's not that complicated, I would change it.
> 
> Did you already tested it again after reverting and merging? Otherwise I will run it again in test-mode.

It took me some tries to because of space characters and stuff - sorry for that - but now I added this missing line. 

I just started a new run in test-mode and will let you know about the outcome.

**Comment by KathiEsterl** [comment]
> > > It should be fine now, I guess?
> > 
> > 
> > One empty line is deleted in `src/egon/data/datasets/industrial_sites/__init__.py`. It will not change the results, but if it's not that complicated, I would change it.
> > Did you already tested it again after reverting and merging? Otherwise I will run it again in test-mode.
> 
> It took me some tries to because of space characters and stuff - sorry for that - but now I added this missing line.
> 
> I just started a new run in test-mode and will let you know about the outcome.

Tested it in test-mode and everything worked fine :+1:

**Review by ClaraBuettner — APPROVED** [review]

**Pull request merged**
