### PR TITLE
Features/#169 renaming gid and subst

### LINKED ISSUE #169: Change gid columns to id columns
VG250 and zensus_vg250 tables use `gid` as name for the primary key column. According to the decision in this should be changed to `id`. Affects

- [ ] All VG250 tables
- [ ] Processing steps that combine vg250 and zensus
- [ ] Potentially all subsequent processing steps that work on data results from the two above

### PR DESCRIPTION
**Pull request by KathiEsterl**
In this version, this branch includes the renaming of columns "gid" to "id: closes #169 
If people are running into errors concerning something about those column names, a delete of the databases content is recommended.

### CODE REVIEW

**Comment by nesnoj** [comment]
Drawback of the additional weekend branch: your changes induced some trouble in 2 tasks in the weekend branch which I fixed accordingly in my affected PRs #260 #421. So I'd be happy if your changes will be merged soon to make those fixes work in dev ;).

**Comment by KathiEsterl** [comment]
> Drawback of the additional weekend branch: your changes induced some trouble in 2 tasks in the weekend branch which I fixed accordingly in my affected PRs #260 #421. So I'd be happy if your changes will be merged soon to make those fixes work in dev ;).

Yes, that was our intention! It should be merged very soon! Thank you!

**Comment by ClaraBuettner** [comment]
I was looking at the changed files and noticed that the version number is not updated in all datasets which are changed. (gas_production, osm, vg250)  Was that intended? 
Right now I can't be sure that all updated functions are executed when I run your branch to check if everything is working.

**Comment by KathiEsterl** [comment]
> I was looking at the changed files and noticed that the version number is not updated in all datasets which are changed. (gas_production, osm, vg250) Was that intended?
> Right now I can't be sure that all updated functions are executed when I run your branch to check if everything is working.

I thought I had adapted all versions in scripts I changed, but maybe I forgot those or something went wrong while merging. Should I just add +1 in the versions in the scripts you just mentioned or how do we solve this?

**Comment by ClaraBuettner** [comment]
> I thought I adapted all versions in scripts I had changed, but maybe I forgot those or something went wrong while merging. Should I just add +1 in the versions in the scripts you just mentioned or how do we solve this?

Yes, you can solve it like this.

**Comment by KathiEsterl** [comment]
> > I thought I adapted all versions in scripts I had changed, but maybe I forgot those or something went wrong while merging. Should I just add +1 in the versions in the scripts you just mentioned or how do we solve this?
> 
> Yes, you can solve it like this.

Sorry, I had to wait for the finish of a local run... It is done now!

**Review by IlkaCu — APPROVED** [review]
The code looks good to me. I didn't test in on my local computer - should I do it prior to merging the branch?

**Comment by ClaraBuettner** [comment]
> The code looks good to me. I didn't test in on my local computer - should I do it prior to merging the branch?

I run it successfully again on my local machine.

**Review by ClaraBuettner — APPROVED** [review]

**Comment by nesnoj** [comment]
Thank you for solving this! :pray:

**Pull request merged**
