### PR TITLE
Features/#291 gas links geom topo

### PR DESCRIPTION
**Pull request by AmeliaNadal**

### CODE REVIEW

**Review by ClaraBuettner — APPROVED** [review]
I run the branch and everything worked fine.

**Comment by AmeliaNadal** [comment]
Thank you @ClaraBuettner! Do you think that I can merge the pull request even if some checks (the 3 first ones) were not successful?

**Comment by ClaraBuettner** [comment]
> Thank you @ClaraBuettner! Do you think that I can merge the pull request even if some checks (the 3 first ones) were not successful?

I think the first two don't fail due to changes on this branch (see #271 ). 
You could improve the results of the Codacy Analysis (at least the `Using an f-string that does not have any interpolated variables (f-string-without-interpolation)` in line 307, you just have to replace  `f"""` with  `"""`).

**Comment by AmeliaNadal** [comment]
Integration of topo and geom in the gas links.

**Pull request merged**
