### PR TITLE
Assign residential heat demand profiles to osm buildings

### LINKED ISSUE #557: Assign heat demand profiles to osm-buildings
The heat demand profiles will be directly assigned to the (synthetic) osm-buildings created in egon-data.

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Closes #557 . 

This branch is a combination of #510 and #489, so it should be merged when the other branches are merged into `dev`.

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by nailend** [comment]
So I ran the pipeline and checked the results for SH. It ran successfully but apparently quite a few census cells go missing during the process but I could figure out why. The existing data seems to be fine though!

image


I used the following SQL-script:
```SQL

SELECT t1.cell_id, array_length(cell_profile_ids, 1) as el_profiles , t1.el_buildings, t3.heat_buildings
FROM demand.egon_household_electricity_profile_in_census_cell as t2

FULL JOIN (
SELECT count(DISTINCT(building_id)) as el_buildings, cell_id
FROM demand.egon_household_electricity_profile_of_buildings
Group by cell_id) as t1
on t1.cell_id = t2.cell_id

FULL JOIN (
SELECT count(zensus_population_id) as heat_buildings, zensus_population_id
FROM demand.heat_timeseries_selected_profiles
Group by zensus_population_id) as t3
ON t1.cell_id = t3.zensus_population_id

ORDER BY t2.cell_id
	
```

**Review by nailend — CHANGES_REQUESTED** [review]
Please check for missing cencus cells in `demand.heat_timeseries_selected_profiles`. Also it would be nice to have a column telling which profiles are multi- or single family houses for the distribution to osm-buildings.
``````SQL

SELECT t1.cell_id, array_length(cell_profile_ids, 1) as el_profiles , t1.el_buildings, t3.heat_buildings
FROM demand.egon_household_electricity_profile_in_census_cell as t2

FULL JOIN (
SELECT count(DISTINCT(building_id)) as el_buildings, cell_id
FROM demand.egon_household_electricity_profile_of_buildings
Group by cell_id) as t1
on t1.cell_id = t2.cell_id

FULL JOIN (
SELECT count(zensus_population_id) as heat_buildings, zensus_population_id
FROM demand.heat_timeseries_selected_profiles
Group by zensus_population_id) as t3
ON t1.cell_id = t3.zensus_population_id

ORDER BY t2.cell_id
	
```

**Comment by ClaraBuettner** [comment]
demand.egon_peta_heat has demands for residential and service heat demand. When you select only the residential heat demands, your statement returns only 3 zensus cells in Germany: 



> Please check for missing cencus cells in `demand.heat_timeseries_selected_profiles`.
> 
> I also compared to the PETA demand. Still there are missing cells having a demand by PETA but no heat demand allocated to buildings. Do you have an idea why this is?

The table demand.egon_peta_heat includes heat demands for residential and service,  `demand.heat_timeseries_selected_profiles` includes only the residential profiles. But even if I adjust your SQL statement some heat profiles are missing. 
This happens at the borders of Germany, so I assume that this is related to the climate_zones. I will check and fix this. 

> 
> Also it would be nice to have a column telling which profiles are multi- or single family houses or even better the building id. Thank you!
> 

I added the building_id to `demand.heat_timeseries_selected_profiles` and merged this branch again into CI-branch. 

> ```sql
> SELECT t1.cell_id,
> 		array_length(cell_profile_ids, 1) as el_profiles ,
> 		t1.el_buildings,
> 		t3.heat_buildings,
> 		t4.peta_demand,
> 		t4.scenario
> FROM demand.egon_household_electricity_profile_in_census_cell as t2
> 
> FULL JOIN (
> SELECT count(DISTINCT(building_id)) as el_buildings, cell_id
> FROM demand.egon_household_electricity_profile_of_buildings
> Group by cell_id) as t1
> on t1.cell_id = t2.cell_id
> 
> FULL JOIN (
> SELECT count(zensus_population_id) as heat_buildings, zensus_population_id
> FROM demand.heat_timeseries_selected_profiles
> Group by zensus_population_id) as t3
> ON t1.cell_id = t3.zensus_population_id
> 
> 
> 
> FULL JOIN (
> SELECT id, demand as peta_demand, zensus_population_id ,scenario
> 	FROM demand.egon_peta_heat
> 	WHERE sector = 'residential'
> ) as t4
> ON t1.cell_id = t4.zensus_population_id
> 
> WHERE heat_buildings is null and peta_demand is not null
> ORDER BY t2.cell_id
> 	
> 	
> ```
> ```

**Comment by ClaraBuettner** [comment]
@nesnoj: #489 and this branch run successfully on CI-branch. 
But #487 includes the task `osm_buildings_streets.extract-buildings-wo-amenities` that never finished in CI runs because it needs too much time. How do we deal with this?

**Comment by nesnoj** [comment]
> @nesnoj: #489 and this branch run successfully on CI-branch.

:+1:

> But #487 includes the task `osm_buildings_streets.extract-buildings-wo-amenities` that never finished in CI runs because it needs too much time. How do we deal with this?

Yes I'm aware of that, it's on my list. I'll fix it asap but after the merges, though I don't like to handle it this way :disappointed: .
I'll take care of the "triple-merge chain".

**Review by nailend — APPROVED** [review]

**Comment by nailend** [comment]
I checked the tables for SH again. Everything looks fine. Thank you for adding the building_id! 
Now its only the few close to the border cells "id" = 1561660 OR "id" = 1573174 OR "id" = 1573376
which will be dealt with in #585

**Comment by nesnoj** [comment]
Thanks for the adjustments!
I did not check the data though as @nailend took care of this.

**Pull request merged**
