### PR TITLE
Features/#5 demandregio integration

### LINKED ISSUE #5: Integrate DemandRegio disaggregator
The DemandRegio data needs to be integrated in egon-data, this can be done by either integrating the DemandRegio Disaggregator or importing the resulting data sets. 
* check if the Ffe Opendata website also provides resulting data set or input data only 
* right now we have a tendency to integrating the tool

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Closes #5 
I integrated demandregio's disaggregator to get the electrical demands per nuts3 for each sector. It also includes scenario-specific adjustments in order to meet either the NEP value or exclude currently electrified heat demands. 
But it still needs some adjustments in the installation of the disaggregator. Currently I added functions which download and install the source code manually from the repo. I'm not sure if this is the best option. At least it is working, but it creates some warnings and a lot of logs.

### CODE REVIEW

**Comment by gplssm** [comment]
You asked for a review, but the PR is still marked as "draft". Please click on "Ready for review" once you're finished. Then, I start to review.
If there open tasks you need help on, don't hesitate to ask!

**Comment by ClaraBuettner** [comment]
I still need to update the installation process of the disaggregator tool. With my last commit I use our fork to install it as a python package. But as we already discussed in #89 we can't publish version on pypi as long as the disaggregator is not published there. 
I will try to move the changes that don't reflect the installation from our disaggregator-fork to my egon-data branch. Then we would not need to publish our fork.

**Comment by ClaraBuettner** [comment]
I just merged this branch with the current dev to avoid problems which were already fixed. This PR is finally ready for your review.

**Comment by IlkaCu** [comment]
I tested the demandRegio integration. Airflow exits without any error, but only three tables are created 
_hh
_cts_ind
_wz
I am missing tables with data on population and households.

**Comment by ClaraBuettner** [comment]
> I tested the demandRegio integration. Airflow exits without any error, but only three tables are created
> _hh
> _cts_ind
> _wz
> I am missing tables with data on population and households.

So you don't get society.egon_demandregio_household and society.egon_demandregio_population? I just deleted these tables and re-run the workflow but I can not reproduce this problem.

**Comment by IlkaCu** [comment]
> > I tested the demandRegio integration. Airflow exits without any error, but only three tables are created
> > _hh
> > _cts_ind
> > _wz
> > I am missing tables with data on population and households.
> 
> So you don't get society.egon_demandregio_household and society.egon_demandregio_population? I just deleted these tables and re-run the workflow but I can not reproduce this problem.

My mistake! I checked the wrong schema. 🙈

**Review by IlkaCu — APPROVED** [review]

**Comment by IlkaCu** [comment]
We should file an additional issue for the integration of DemandRegio's load curves.

**Comment by IlkaCu** [comment]
@ClaraBuettner: Please add a comment in the CHANGELOG to describe what you've added.

**Comment by gplssm** [comment]
I wanted to test once at least, but I constantly run into the following error
`[2021-02-09 18:57:00,611] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedFile) could not access file "$libdir/postgis-2.5": No such file or directory`
which seems to be unrelated to this PR.
For some reason, psycopg2 looks for postgis 2.5 instead of using version 3 which is specified in the `docker-compose.yml`.

**Review by gplssm — APPROVED** [review]
Since it looks like @IlkaCu could verify execution of new code and I looked through the code, I'd approve without further testing to execute it.

**Comment by ClaraBuettner** [comment]
> I wanted to test once at least, but I constantly run into the following error
> `[2021-02-09 18:57:00,611] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedFile) could not access file "$libdir/postgis-2.5": No such file or directory`
> which seems to be unrelated to this PR.
> For some reason, psycopg2 looks for postgis 2.5 instead of using version 3 which is specified in the `docker-compose.yml`.

Just to be sure that this problem has nothing to do with this branch, I tested the installation again and didn't run into this error.

**Comment by gplssm** [comment]
> > I wanted to test once at least, but I constantly run into the following error
> > `[2021-02-09 18:57:00,611] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedFile) could not access file "$libdir/postgis-2.5": No such file or directory`
> > which seems to be unrelated to this PR.
> > For some reason, psycopg2 looks for postgis 2.5 instead of using version 3 which is specified in the `docker-compose.yml`.
> 
> Just to be sure that this problem has nothing to do with this branch, I tested the installation again and didn't run into this error.

Correct! It was due to my local configuration and just appeared here. I resolved it and report the solution in https://github.com/openego/eGon-data/issues/113#issuecomment-776829712. 
Meanwhile, I was able to run the entire workflow including demandRegio and zensus part.

**Pull request merged**
