### PR TITLE
Features/#4 osmtgmod

### LINKED ISSUE #4: Include osmTGmod
Integrate the osmTGmod tool into the egon-data workflow. 
Clarify if we can keep the table structure and if the data should be published at the OEP.

### LINKED ISSUE #115: include pgrouting extension
For #4 it is necessary to have the extension pgrouting. Unfortunately, so far I was not able to get this extension working. osmTGmod throws an error stating that the pgrouting.control file is missing in the extensions folder of postgresql (/usr/share/postgresql/12/extension).

I tried numerous things. Withing egon-data I tried out 31af5bdbf9b3b7e3d58a26f31add64b425793650

Furthermore I tried this: https://docs.pgrouting.org/3.0/en/pgRouting-installation.html
It is failing because boost was not available when executing the cmake command. Installing boost did not work either.

I also found this: https://github.com/pgRouting/docker-pgrouting
which so far did not lead to anything really. To change our docker to this image seems to be most promising to me though right now.

### LINKED ISSUE #163: osmTGmod (resp. osmosis) needs java as a prequisite
Dealing with #4 I had to install java via https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-on-ubuntu-18-04-de

How do we add this to our repos?

### PR DESCRIPTION
**Pull request by ulfmueller**
handles #4 in particular does:
- takes the downloaded osm file from the egon-data process as a base
- uses the substation buses from the egon-data process for topology fixes
- uses db connection from the egon-data process
- updates pgsql functions within osmTGmod due to the usage of a newer versions
- clones the osmTGmod github repos into the local egon-data
- works fine for the Schleswig-Holstein dataset and should work for entire Germany (not tested yet)
- pgrouting and java need to be installed as a prequisite. Concerning pgrouting (see  #115 ), reviewers, especially @gnn please check if 31af5bdbf9b3b7e3d58a26f31add64b425793650 works for you. Concerning java, @gnn how do we add this prequisite (see #163 )?
- closes #4 
- closes #115 
- closes #163

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
I tried to run this branch but I ran into errors that might be connected to pgrouting. 
First, the task 'osmtgmod' faild with this error message: 

```
> Traceback (most recent call last):
>   File "/home/clara/venv/egon-data/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
>     result = task_copy.execute(context=context)
>   File "/home/clara/venv/egon-data/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
>     return_value = self.execute_callable()
>   File "/home/clara/venv/egon-data/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
>     return self.python_callable(*self.op_args, **self.op_kwargs)
>   File "/home/clara/GitHub/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 45, in run_osmtgmod
>     docker_db_config=docker_db_config)
>   File "/home/clara/GitHub/eGon-data/src/egon/data/processing/osmtgmod/__init__.py", line 205, in osmtgmod
>     cur.execute(sqlfile)
> psycopg2.errors.UndefinedFile: could not open extension control file "/usr/share/postgresql/12/extension/pgrouting.control": No such file or directory
```
I think this was caused because the container was not created with the new image. So I removed the docker container to get a new one with pgrouting (just restarting it didn't seemed to help). But now I run into an error in 'initdb'. The log is very long, I add only the last rows. If you need it, I can also post all lines
```
> |   E: Failed to fetch http://deb.debian.org/debian/pool/main/x/xerces-c
> |   /libxerces-c3.2_3.2.2+debian-1+b1_amd64.deb  404  Not Found [IP:
> |   199.232.138.132 80]
> |   E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main
> |   /p/postgis/postgresql-12-postgis-3-scripts_3.0.2+dfsg-4.pgdg100+1_al
> |   l.deb  404  Not Found [IP: 217.196.149.55 80]
> |   E: Failed to fetch http://apt.postgresql.org/pub/repos/apt/pool/main
> |   /p/postgis/postgresql-12-postgis-3_3.0.2+dfsg-4.pgdg100+1_amd64.deb
> |   404  Not Found [IP: 217.196.149.55 80]
> |   E: Unable to fetch some archives, maybe run apt-get update or try
> |   with --fix-missing?
> |   [0mFetched 39.9 MB in 13s (3,106 kB/s)
> | Errors:
> |   Building egon-data-local-database
> |   Service 'egon-data-local-database' failed to build: The command
> |   '/bin/sh -c apt-get install -y postgresql-12-postgis-3
> |   postgresql-12-pgrouting' returned a non-zero code: 100
> 

```
I tried the last command of @gnn in #115 and added the `/etc/docker/daemon.json` but I still get these errors. I also tried to add the IPs which are marked as 'Not Found' in the log to `/etc/docker/daemon.json` but it didn't help.

**Comment by ClaraBuettner** [comment]
I tried to manually install `postgresql-12-pgrouting` inside the running docker container and that worked. I was able to add the pgrouting extension. But I don't know why this works and the automatic installation fails. 
@ulfmueller Do you remember if you also installed it manually or directly via the Dockerfile.postgis?

**Comment by ulfmueller** [comment]
Yes, I think I also installed it manually in the end but I hoped that @gnn solution would work in another environment.
@gnn do you have a solution for this issue?

**Comment by gnn** [comment]
> I tried to run this branch but I ran into errors that might be connected to pgrouting.
> First, the task 'osmtgmod' faild with this error message:
> 
> ```
> > psycopg2.errors.UndefinedFile: could not open extension control file "/usr/share/postgresql/12/extension/pgrouting.control": No such file or directory
> ```
> 
> I think this happened because the container was not created with the new image.

This is indeed correct. Rebuilding the container gets moved out of Airflow and into the CLI startup, where we should have better control over it, on the "option-testmode" branch which I'm still in the process of merging. When this is done, the container hopefully gets rebuild automatically when the installation commands change.

> So I removed the docker container to get a new one with pgrouting (just restarting it didn't seemed to help). But now I run into an error in 'initdb'. The log is very long, I add only the last rows. If you need it, I can also post all lines

I think I can gather enough information from the fragment you posted. If you want to post long logs in the future though, you could upload them as a [gist][0] or to [0bin][1], [or][5] [to][6] [some][2] [similar][3] [service][4][,][7] and post the link.
These are similar errors to the ones I got in issue #115. There's a longer explanation below.

[0]: https://gist.github.com
[1]: https://0bin.net/
[5]: http://p.ip.fi
[2]: https://zerobin.net
[3]: https://cryptobin.co
[4]: https://paste.ee
[6]: http://codepad.org
[7]: https://www.friendpaste.com
> I tried the last command of @gnn in #115 and added the `/etc/docker/daemon.json` but I still get these errors.

Did you also restart you Docker service via `sudo systemctl restart docker.service`?

> I tried to manually install `postgresql-12-pgrouting` inside the running docker container and that worked. I was able to add the pgrouting extension. But I don't know why this works and the automatic installation fails.

You probably rebooted since your last post, which means that your Docker service got restarted. So unless you restarted it manually beforehand, that might already be the solution.

> > @ulfmueller Do you remember if you also installed it manually or directly via the Dockerfile.postgis?
>
> Yes, I think I also installed it manually in the end but I hoped that @gnn solution would work in another environment.
> @gnn do you have a solution for this issue?

Not sure. Right now I still can't be sure whether adjusting `/etc/docker/daemon.json` fixes the issue reliably. On the other hand, the issue isn't specific to your additions. If installing `postgresql-12-pgrouting` fails due to network problems, installing `postgresql-12-postgis-3` should also fail due to the same problems. And that worked for everybody so far.

Now here's a longer explanation about the errors we saw:
> I also tried to add the IPs which are marked as 'Not Found' in the log to `/etc/docker/daemon.json` but it didn't help.

No need for that. The reason why those IP addresses are not found is that the Docker container has some kind of trouble connecting to the internet. For me the problem was that the container did not pick up the domain name service (DNS) configured on my host machine, so the container could not resolve a name like "apt.postgresql.org" to an IP address. This is what the `dns:` entry in `/etc/docker/daemon.json` is for. It's the IP address of a public DNS server, which the container can use to resolve addresses. So on the one hand, I'm pretty sure that I got the same errors as you. On the other hand, the fact that IP addresses show up in the error messages, is a hint at a working DNS server. And since you got 404 errors, it means that the server was reachable, but the requested URLs where not found on the servers. Looking at the IP addresses, it also seems that name resolution worked: `199.232.138.132` is a valid IP address for `deb.debian.org` and `217.196.149.55` is a valid address for `apt.postgresql.org`. It just seems that those services where down or not working correctly at the time you tried to access them.

`¯\_(ツ)_/¯`

**Comment by ClaraBuettner** [comment]
> I think I can gather enough information from the fragment you posted. If you want to post long logs in the future though, you could upload them as a [gist](https://gist.github.com) or to [0bin](https://0bin.net/), [or](http://p.ip.fi) [to](http://codepad.org) [some](https://zerobin.net) [similar](https://cryptobin.co) [service](https://paste.ee)[,](https://www.friendpaste.com) and post the link.
> These are similar errors to the ones I got in issue #115. There's a longer explanation below.
> 
> > I tried the last command of @gnn in #115 and added the `/etc/docker/daemon.json` but I still get these errors.
> 
> Did you also restart you Docker service via `sudo systemctl restart docker.service`?

Thank you for your help. I am sure I did this several times. 
I just removed my docker container again and re-tried to run this branch. I still get the error I had before. So rebooting doesn't seem to be the solution. 

The only difference  in the manual installation was that postgresql and postgis were already installed when I installed postgresql-12-pgrouting. 
So I tested one thing which seemed to be useless and divided the line

`RUN apt-get install -y postgresql-12-postgis-3 postgresql-12-pgrouting`

in Dockerfile.postgis into two lines: 
```
RUN apt-get install -y postgresql-12-postgis-3
RUN apt-get install -y postgresql-12-pgrouting
```

And everything worked fine. PgRouting was installed correctly and the whole workflow ran successful. 
I have no idea why this worked, I thought that dividing it into two lines doesn't change anything. But maybe this is the solution?

**Comment by ClaraBuettner** [comment]
I couldn't find which tables should be added in a configuration file or something similar. The resulting tables are stored in the public schema. Nothing is added or inserted in the grid schema. Is that correct @ulfmueller?

**Comment by ClaraBuettner** [comment]
I checked it again and removed my docker container. With 
`RUN apt-get install -y postgresql-12-postgis-3 postgresql-12-pgrouting`
it fails and with 
```
RUN apt-get install -y postgresql-12-postgis-3
RUN apt-get install -y postgresql-12-pgrouting
```
it works. So I changed this in 3f9fae2 

Besides, I also have some other questions:
I'm not very happy with the schema name 'results' because it doesn't really help to find the output of osmTGmod (at least I couldn't find it.) Would changing the name to something like 'osmtgmod' lead to many changes? Otherwise it could be also an option keep the name and just document it, e.g. in datasets.yml. 

There are some issue in Codacy which could be resolved (automatically).

Could you add a note to the changelog?

**Comment by ulfmueller** [comment]
Thx for your checking @ClaraBuettner and finding a solution for the pgrouting installation!

I will check the results schema task, tackle the codacy and add a changelog entry.
For the last two mentioned. How do I resolve the codacy issues automatically?
I am not familiar with our changelog. Can you roughly tell me what to do?

**Comment by ClaraBuettner** [comment]
> Thx for your checking @ClaraBuettner and finding a solution for the pgrouting installation!
> 
> I will check the results schema task, tackle the codacy and add a changelog entry.
> For the last two mentioned. How do I resolve the codacy issues automatically?

I sometimes format the code automatically with black (which is an option of Spyder, as described in the last comment 
[here](https://stackoverflow.com/questions/55698077/how-to-use-code-formatter-black-with-spyder)), this resolves the most codacy issues (like too long lines or wrong indentation...). 

> I am not familiar with our changelog. Can you roughly tell me what to do?

You just write one short comment what you have integrated and link to the issue. Since you have implemented something new I would add it to the 'Added'-part. There are already a lot of examples in the current file.

**Pull request merged**
