### PR TITLE
Add HH load area profile generator

### LINKED ISSUE #256: Household load areas and demand profiles
Load areas of household sector and related peak load/annual demand area identified

### LINKED ISSUE #294: Use 100.000 household demand profiles instead of 10.000
With #256 household electricity demand profiles got integrated into egon-data. At this step, 10.000 profiles where used in total. Replace the 10.000 profiles by 100.000 which we got from IEE.

### Tasks

- [ ] Merge 3 `.h5` files
- [ ] Test if code works well with 100.000 profiles
- [ ] Upload to existing Zenodo deposit with heat demand profiles
- [ ] Add metadata according to mail discussion

cf. mail on 17.6.21

### LINKED ISSUE #295: Insert household demand time series into database
Currently, raw data of household electricity demand time series is read from a `.h5` file (accessible through a function). For easier access, in particular, when mapping of zensus cells and household profile IDs is published on OEP, it makes sense to have the profile on OEP as well. Therefore, during the workflow household demand time series should be inserted into the database.

But, please consider

- It's quite an amount of data (~6 GB `.h5`) which doubles up in the container's volume
- It needs to be documented in the mapping table that profile IDs link to this table
- Data access from file needs to be replaced by database access

### PR DESCRIPTION
**Pull request by gplssm**
Add household electricity demand time series, mapping of demand profiles to census cells and aggregated household electricity demand time series at MV grid district level.

Newly created in tables (from the docs)

- `demand.household_electricity_profiles_in_census_cells`: Lists references and scaling parameters to time series data for each household in a cell by identifiers. This table is fundamental for creating subsequent data like demand profiles on MV grid level or for determining the peak load at load area level
- `demand.household_electricity_profiles_hvmv_substation`:   Household electricity demand profiles aggregated at MV grid district level.

For the review

@ClaraBuettner please have a detailed look on the second table. And if you have time, we're interested in general feedback

@gnn Could you please have a look on https://github.com/openego/eGon-data/pull/260#issuecomment-864936520

TODO:

- [x] check dataset.yml for correct paths after datasets were included into databundle 
- [x] add fixed seed for random generator
- [x] change to global seed
- [x] add metadata according to mail discussion with @gplssm cf. mail on 17.6.21

Fixes #256 
Fixes #294 
Fixes #295

### CODE REVIEW

**Comment by nailend** [comment]
This is almost done but running it we ended up in the following airflow task error:

The task `mv_HH_electricity_load_****` is called twice for different projection years 2035 and 2050. Calling it the first time, the old table of `demand.egon_etrago_electricity_households` is dropped. The second time the results are appended  but the task creates the following error although the created data exists in the db table and seems to be complete. @gnn do you have an idea, where this is coming from?


```[2021-06-18 19:07:17,868] {taskinstance.py:1150} ERROR - 'PostgresOperator' object has no attribute 'dataset'
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/julian.endres/miniconda3/envs/egon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 191, in skip_task
    function(session)
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 202, in update
    [
  File "/home/local/RL-INSTITUT/julian.endres/Projekte/eGon-data/src/egon/data/datasets/__init__.py", line 206, in <listcomp>
    dependency.dataset
AttributeError: 'PostgresOperator' object has no attribute 'dataset'
[2021-06-18 19:07:17,869] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=mv_HH_electricity_load_2050, execution_date=20210618T163505, start_date=20210618T170554, end_date=20210618T170717
[2021-06-18 19:07:20,088] {local_task_job.py:102} INFO - Task exited with return code 1```

**Comment by nailend** [comment]
Same task error happens implementing versioning with further datasets (see https://github.com/openego/eGon-data/issues/297#issuecomment-865904336). @gnn is this connected to the direct use of the dataset class in https://github.com/openego/eGon-data/blob/b2d8b33b4d13e5eda3d6687e2f085a69cb299615/src/egon/data/airflow/dags/pipeline.py#L586-L597?

**Comment by nailend** [comment]
> Same task error happens implementing versioning with further datasets (see [#297 (comment)](https://github.com/openego/eGon-data/issues/297#issuecomment-865904336)). @gnn is this connected to the direct use of the dataset class in

This seems to be an expected error in the versioning module which concerns only further dependencies. Will be fixed in #298

**Comment by ClaraBuettner** [comment]
I tested this branch for `--dataset-boundary 'Schleswig-Holstein'`. The last task `MV-hh-electricity-load-2050` fails with `AttributeError: 'PostgresOperator' object has no attribute 'dataset'`, but it looks like this will be solved in another issue. 

I had a look into the table `demand.household_electricity_profiles_hvmv_substation`. It includes all the data needed for eTraGo, I am just wondering if it would be possible to call it 'bus_id' instead of 'subst_id' because it will be also called 'bus_id' in the following scripts and tables. 
Regarding the new tasks and dependencies, I also have one more general question: Are you not using the household_prognosis at all? I know that there are problem because of missing data on household types, so I'm wondering if we really need the household_prognosis.

**Comment by nailend** [comment]
> I tested this branch for `--dataset-boundary 'Schleswig-Holstein'`. The last task `MV-hh-electricity-load-2050` fails with `AttributeError: 'PostgresOperator' object has no attribute 'dataset'`, but it looks like this will be solved in another issue.

Yes, I am only waiting for the PR of @gnn of [features/#298-allow-unversioned-tasks-as-dataset-dependencies ](https://github.com/openego/eGon-data/tree/features/%23298-allow-unversioned-tasks-as-dataset-dependencies)

> Regarding the new tasks and dependencies, I also have one more general question: Are you not using the household_prognosis at all? I know that there are problem because of missing data on household types, so I'm wondering if we really need the household_prognosis.

I am not sure if I understand the question right but I will try to answer it anyways and please correct me if I guessed wrongly.
The distribution of the household profiles is done by a merge of zensus data at 100x100 cell level and federal state level (as the cell level is not detailed enough to fit the the profile classes of the profile generator). The profiles are later on scaled with the demand-regio projections at nuts3 level for 2035 and 2050. The zensus data used for the distribution is from 2011 and therefore no prognosis.

**Comment by nailend** [comment]
> I tested this branch for `--dataset-boundary 'Schleswig-Holstein'`. The last task `MV-hh-electricity-load-2050` fails with `AttributeError: 'PostgresOperator' object has no attribute 'dataset'`, but it looks like this will be solved in another issue.
> 
> I had a look into the table `demand.household_electricity_profiles_hvmv_substation`. It includes all the data needed for eTraGo, I am just wondering if it would be possible to call it 'bus_id' instead of 'subst_id' because it will be also called 'bus_id' in the following scripts and tables.

@ClaraBuettner  can I merge this then?

**Comment by nesnoj** [comment]
Could u merge the dev into your branch first to make sure the latest updates are included?

**Comment by nesnoj** [comment]
I ran the test region and saw that at least in some cells the number of HH as given in `society.egon_destatis_zensus_household_per_ha` (column `INSGESAMT`) does not match the number of allocated profiles. 

Example: grid_id **100mN35212E42841**
- `society.egon_destatis_zensus_household_per_ha`: 10
- `demand.household_electricity_profiles_in_census_cells`: 9 profiles ({SR,190}, {SO,698}, {SO,1327}, {P1,627}, {P2,88}, {P3,103}, {OR,5}, {OR,90}, {OO,747})

Ah, hang on, I just see that you're using `HHGROESS_KLASS` and `HHTYP_FAM` which sums up to 9 entities. And the dataset description says for `INSGESAMT`: "Kann aufgrund der Geheimhaltung  von der Summe über alle Ausprägungen der anderen Merkmale abweichen". So this is probably ok.

2 questions:
- Did you check how large's the deviation of the data between those 2 attributes? (1 as in the above example is ok but if it's something like 50%...well...)
- Did you make use of the `quantity_q` attribute which describes the data quality?

(BTW: I started a full DE run too...)

**Comment by nesnoj** [comment]
One more thing: The use of the attributes `HHGROESS_KLASS` and `HHTYP_FAM` might be problematic as some cells (e.g. **100mN33624E43594**) do not provide data for there 2 fields, only for `INSGESAMT`. Could you check how many cells are affected to see if it's worth to modify the methods?

**Comment by nesnoj** [comment]
@ClaraBuettner I can take care of the remaining stuff and removed you as reviewer.. if you are keen on reviewing this, please re-add yourself.

**Comment by nesnoj** [comment]
> One more thing: The use of the attributes `HHGROESS_KLASS` and `HHTYP_FAM` might be problematic as some cells (e.g. **100mN33624E43594**) do not provide data for there 2 fields, only for `INSGESAMT`. Could you check how many cells are affected to see if it's worth to modify the methods?

For documentation purposes:
- `HHGROESS_KLASS` is currently not used
- As written in RC with @nailend, about 6% of cells lack `HHTYP_FAM` data. Idea: assume average split from cells having `HHGROESS_KLASS` for cells without this attribute (and scale using `INSGESAMT`).

**Comment by nesnoj** [comment]
@nailend I just stumbled across another thing:
You make use of `demand.egon_demandregio_hh` the in `adjust_to_demand_regio_nuts3_annual()` to scale up the profiles. There's the table `demand.egon_demandregio_zensus_electricity` where the demand is stored per cell and sector. In the end I guess it doesn't matter - u might be even faster - but I just wanted to make sure you're aware of the table. I compared the data with the one from `demand.egon_demandregio_hh` and it looks consistent.

```sql
SELECT scenario, sector, vg.vg250_nuts3, sum(demand)
	FROM demand.egon_demandregio_zensus_electricity dr
	JOIN boundaries.egon_map_zensus_vg250 vg
	USING (zensus_population_id)
	GROUP BY vg.vg250_nuts3, scenario, sector
	ORDER BY vg.vg250_nuts3, scenario, sector;
```

**Comment by nesnoj** [comment]
> (BTW: I started a full DE run too...)

The run failed, see log below. It cannot find 'Baden-Württemberg (Bodensee)' in your countries. Looks like a filter error as VG250 contains the seas and some large water bodies which must be excluded before (key "GF" - Geofaktor, cf. [docs](https://sg.geodatenzentrum.de/web_download/vg/vg250-ew_3112/vg250-ew_3112.pdf)), only entries with GF=4 should be used. I'll fix this.

```
*** Reading local file: /home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/egon-data/airflow/logs/egon-data-processing-pipeline/hh_demand_profiles.houseprofiles-in-census-cells/2021-07-26T10:54:49.272590+00:00/1.log
[2021-07-27 15:10:02,201] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.hh_demand_profiles.houseprofiles-in-census-cells 2021-07-26T10:54:49.272590+00:00 [queued]>
[2021-07-27 15:10:02,271] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.hh_demand_profiles.houseprofiles-in-census-cells 2021-07-26T10:54:49.272590+00:00 [queued]>
[2021-07-27 15:10:02,271] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-07-27 15:10:02,271] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-07-27 15:10:02,271] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-07-27 15:10:02,322] {taskinstance.py:901} INFO - Executing <Task(HH Demand (versioned)): hh_demand_profiles.houseprofiles-in-census-cells> on 2021-07-26T10:54:49.272590+00:00
[2021-07-27 15:10:02,335] {standard_task_runner.py:54} INFO - Started process 26153 to run task
[2021-07-27 15:10:02,507] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'hh_demand_profiles.houseprofiles-in-census-cells', '2021-07-26T10:54:49.272590+00:00', '--job_id', '232', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmp9tate392']
[2021-07-27 15:10:02,508] {standard_task_runner.py:78} INFO - Job 232: Subtask hh_demand_profiles.houseprofiles-in-census-cells
[2021-07-27 15:10:02,663] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.hh_demand_profiles.houseprofiles-in-census-cells 2021-07-26T10:54:49.272590+00:00 [running]> on host srvsim01.rl-institut.local
[2021-07-27 15:12:52,407] {taskinstance.py:1150} ERROR - 'Baden-Württemberg (Bodensee)'
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Baden-Württemberg (Bodensee)'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/__init__.py", line 192, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/hh_demand_profiles.py", line 887, in houseprofiles_in_census_cells
    df_country_type["factor"] = df_dist_households.loc[typ, country]
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 862, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/generic.py", line 3773, in xs
    loc = index.get_loc(key)
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Baden-Württemberg (Bodensee)'
[2021-07-27 15:12:52,423] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=hh_demand_profiles.houseprofiles-in-census-cells, execution_date=20210726T105449, start_date=20210727T151002, end_date=20210727T151252
[2021-07-27 15:12:53,353] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by nesnoj** [comment]
After having fixed the state problem above, I'm getting
```
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/hh_demand_profiles.py", line 918, in houseprofiles_in_census_cells
    df_cell_demand_metadata = get_cell_demand_metadata(
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/hh_demand_profiles.py", line 642, in get_cell_demand_metadata
    cell_profile_ids = get_cell_demand_profile_ids(df_cell, pool_size)
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/hh_demand_profiles.py", line 571, in get_cell_demand_profile_ids
    cell_profile_ids = [
  File "/home/local/RL-INSTITUT/jonathan.amme/git-repos/openego/eGon-data/src/egon/data/datasets/hh_demand_profiles.py", line 572, in <listcomp>
    (hh_type, random.sample(range(pool_size[hh_type]), k=sq))
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/random.py", line 363, in sample
    raise ValueError("Sample larger than population or is negative")
```
That means 10k profiles are not sufficient for entire DE, right @nailend?

**Comment by nesnoj** [comment]
@nailend The DE run was successful :smile_cat: (took 3h)
As soon as you have integrated the handling of missing cells and the GF filter, I'll restart the run and give the data some plausibility checks afterwards. If you can make it today, I can do the check tomorrow - otherwise this PR will remain unmerged until I return from my vacation.

**Comment by nesnoj** [comment]
Damn, but the tasks `mv_grid_district_HH_electricity_load` for both years failed:
```
[SQL: INSERT INTO xcom (key, value, timestamp, execution_date, task_id, dag_id) VALUES (%(key)s, %(value)s, %(timestamp)s, %(execution_date)s, %(task_id)s, %(dag_id)s) RETURNING xcom.id]
[parameters: {'key': 'return_value', 'value': <psycopg2.extensions.Binary object at 0x7fe3ae84b330>, 'timestamp': datetime.datetime(2021, 7, 28, 16, 16, 28, 157642, tzinfo=<Timezone [UTC]>), 'execution_date': <Pendulum [2021-07-26T10:54:49.272590+00:00]>, 'task_id': 'MV-hh-electricity-load-2035', 'dag_id': 'egon-data-processing-pipeline'}]
(Background on this error at: http://sqlalche.me/e/13/2j85)
Traceback (most recent call last):
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/local/RL-INSTITUT/jonathan.amme/virtualenvs/eGon-data/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: invalid memory alloc request size 1073741824
```
Looks like a similar problem as in #196 
Will try to fix...

**Comment by nesnoj** [comment]
Update on the `mv_grid_district_HH_electricity_load` task:
You convert everything to a dict and make use of SQLAlchemy's `bulk_insert_mappings()`. This approach is acceptable for a hand full of bytes but as far as I understand, the entire data is included in the SQL statement which subsequently exceeds the query buffer of 1 GB (error log above says 1073741824 which is 1024^3 bytes = 1 GB).
I'm testing if SQLA's native insert does better..

**Comment by nesnoj** [comment]
> As proposed by you @nailend, could you please try `pandas.to_sql()` instead?

According to @gnn we could also chunk the data manually prior to inserting ([example](https://github.com/open-fred/cli/blob/c2fb7e1d7bce8b8c9bd0104dff94d1a04151cfa2/src/open_FRED/cli.py#L382)) while keeping the bulk insert function, it doesn't really matter if you do it this way or make use of `pandas.to_sql()`. Are u gonna take care of this or shall I?

**Comment by nailend** [comment]
> Are u gonna take care of this or shall I?

I will implement the `to_sql()` version if you have no further reason to keep the `bulk_insert`

**Comment by nesnoj** [comment]
> > Are u gonna take care of this or shall I?
> 
> I will implement the `to_sql()` version if you have no further reason to keep the `bulk_insert`

:+1:

BTW, the [link](https://github.com/openego/eGon-data/blob/1b22726f847419c503ea9ae36a23cbe667b88c46/src/egon/data/datasets.yml#L443) to the `Zensus2011_Personen.csv` seems to be dead, but it's part of the datapackage already and we have to switch to the new source anyway..

**Comment by nailend** [comment]
> > > Are u gonna take care of this or shall I?
> > 
> > 
> > I will implement the `to_sql()` version if you have no further reason to keep the `bulk_insert`
> 
> +1
> 
> BTW, the [link](https://github.com/openego/eGon-data/blob/1b22726f847419c503ea9ae36a23cbe667b88c46/src/egon/data/datasets.yml#L443) to the `Zensus2011_Personen.csv` seems to be dead, but it's part of the datapackage already and we have to switch to the new source anyway..

yes, saw this and fixed it locally with a spare link

**Comment by nailend** [comment]
The data will now be imported from the data-bundle. If the files don't exist, they will be downloaded from the nextcloud for now.

**Comment by nesnoj** [comment]
Thanks for the updates!
As the data bundle #356 is now up-to-date you can remove the nextcloud part.

**Comment by nesnoj** [comment]
The full DE run just finished:
`hh_demand_profiles.houseprofiles-in-census-cells` was successful :tada: but the downstream tasks `MV-hh-electricity-load-2035` (and 2050) were not :disappointed:.
For the latter I'm getting `sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) invalid memory alloc request size 1073741824` - same error as before (see [above](https://github.com/openego/eGon-data/pull/260#issuecomment-888838407)). 

<details>
  <summary>For full log click here</summary>

```
[2021-08-24 13:39:18,793] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.MV-hh-electricity-load-2035 2021-08-23T15:25:31.249276+00:00 [queued]>
[2021-08-24 13:39:18,884] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.MV-hh-electricity-load-2035 2021-08-23T15:25:31.249276+00:00 [queued]>
[2021-08-24 13:39:18,885] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-08-24 13:39:18,885] {taskinstance.py:881} INFO - Starting attempt 1 of 1
[2021-08-24 13:39:18,885] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-08-24 13:39:18,894] {taskinstance.py:901} INFO - Executing <Task(HH Demand (versioned)): MV-hh-electricity-load-2035> on 2021-08-23T15:25:31.249276+00:00
[2021-08-24 13:39:18,901] {standard_task_runner.py:54} INFO - Started process 3580135 to run task
[2021-08-24 13:39:18,949] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'MV-hh-electricity-load-2035', '2021-08-23T15:25:31.249276+00:00', '--job_id', '159', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmptle9gbhp']
[2021-08-24 13:39:18,950] {standard_task_runner.py:78} INFO - Job 159: Subtask MV-hh-electricity-load-2035
[2021-08-24 13:39:18,993] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.MV-hh-electricity-load-2035 2021-08-23T15:25:31.249276+00:00 [running]> on host at32
[2021-08-24 13:41:53,688] {utils.py:145} INFO - Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-08-24 13:41:53,688] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2021-08-24 14:24:01,853] {python_operator.py:114} INFO - Done. Returned value was:       subst_id  ...  scn_name
0        29061  ...  eGon2035
1        29063  ...  eGon2035
2        29065  ...  eGon2035
3        29066  ...  eGon2035
4        29067  ...  eGon2035
...        ...  ...       ...
3773     34194  ...  eGon2035
3774     34196  ...  eGon2035
3775     34198  ...  eGon2035
3776     34199  ...  eGon2035
3777     34200  ...  eGon2035

[3778 rows x 4 columns]
[2021-08-24 14:24:15,441] {taskinstance.py:1150} ERROR - (psycopg2.errors.InternalError_) invalid memory alloc request size 1073741824

[SQL: INSERT INTO xcom (key, value, timestamp, execution_date, task_id, dag_id) VALUES (%(key)s, %(value)s, %(timestamp)s, %(execution_date)s, %(task_id)s, %(dag_id)s) RETURNING xcom.id]
[parameters: {'key': 'return_value', 'value': <psycopg2.extensions.Binary object at 0x7f51b01135d0>, 'timestamp': datetime.datetime(2021, 8, 24, 12, 24, 3, 72402, tzinfo=<Timezone [UTC]>), 'execution_date': <Pendulum [2021-08-23T15:25:31.249276+00:00]>, 'task_id': 'MV-hh-electricity-load-2035', 'dag_id': 'egon-data-processing-pipeline'}]
(Background on this error at: http://sqlalche.me/e/13/2j85)
Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.InternalError_: invalid memory alloc request size 1073741824


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 988, in _run_raw_task
    self.xcom_push(key=XCOM_RETURN_KEY, value=result)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1508, in xcom_push
    XCom.set(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/airflow/models/xcom.py", line 120, in set
    session.commit()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1046, in commit
    self.transaction.commit()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 504, in commit
    self._prepare_impl()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 483, in _prepare_impl
    self.session.flush()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2540, in flush
    self._flush(objects)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2682, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2642, in _flush
    flush_context.execute()
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/egondata/git-repos/friday-evening-weekend-run/environment/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) invalid memory alloc request size 1073741824

[SQL: INSERT INTO xcom (key, value, timestamp, execution_date, task_id, dag_id) VALUES (%(key)s, %(value)s, %(timestamp)s, %(execution_date)s, %(task_id)s, %(dag_id)s) RETURNING xcom.id]
[parameters: {'key': 'return_value', 'value': <psycopg2.extensions.Binary object at 0x7f51b01135d0>, 'timestamp': datetime.datetime(2021, 8, 24, 12, 24, 3, 72402, tzinfo=<Timezone [UTC]>), 'execution_date': <Pendulum [2021-08-23T15:25:31.249276+00:00]>, 'task_id': 'MV-hh-electricity-load-2035', 'dag_id': 'egon-data-processing-pipeline'}]
(Background on this error at: http://sqlalche.me/e/13/2j85)
[2021-08-24 14:24:15,487] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=MV-hh-electricity-load-2035, execution_date=20210823T152531, start_date=20210824T113918, end_date=20210824T122415
[2021-08-24 14:24:16,846] {local_task_job.py:102} INFO - Task exited with return code 1
```
</details>

Responsible code:
https://github.com/openego/eGon-data/blob/e09b7697c8d7eaa4c2a90f79eb1b4a8af4d94b2a/src/egon/data/datasets/hh_demand_profiles.py#L1469-L1478
Any recommendations @nailend , should we try decrease the chunksize?

**Comment by nesnoj** [comment]
I tried 1000 and 100, same result :hankey:

**Comment by nesnoj** [comment]
We solved the `invalid memory alloc request` error! :partying_face: 
It wasn't caused by to_sql() but by returning the DF to the pipeline (legacy code from dataset migration), dunno why this is a problem. (@gnn so we don't need code snippets on this anymore)

2035 ran successfully, 2050 is ongoing - will report.
@nailend Please add the random seed #351 and check the [contributing guidelines](https://egon-data.readthedocs.io/en/latest/contributing.html) if there's anything missing..

**Comment by nailend** [comment]
Merged into weekend-run-branch

**Review by nesnoj — APPROVED** [review]
This one has been tested a couple of times now, everything works as expected. :tada: 
Thank you @gplssm and @nailend for your efforts during the last months (111 commits!), this dataset is an important part of the database and will also improve ding0's DGs!

Caution: In #428 some columns have been renamed, a fix to the present PR has been added in 1fbd656dbeb7d6cdb0c641dbf86cbdf4746a120b, it requires #428 to work.

**Pull request merged**
