### PR TITLE
Replace pandas.datetime with datetime,datetime

### LINKED ISSUE #516: datetime.datetime should be used instead of pd.datetime
The `heat_demand_timeseries.HTS` module calls the `pandas.datetime` function in some places. It should be `datetime.datetime` to avoid trouble with future versions of pandas: https://stackoverflow.com/questions/60856866/why-is-datetime-being-removed-from-pandas.

### PR DESCRIPTION
**Pull request by fwitte**
Resolve #516

### CODE REVIEW

**Comment by IlkaCu** [comment]
Please update CHANGELOG file and increase the version number of class HeatTimeSeries.

**Review by IlkaCu — CHANGES_REQUESTED** [review]
> Please update CHANGELOG file and increase the version number of class HeatTimeSeries.

**Comment by fwitte** [comment]
Should we merge this into CI before we merge into dev?

**Comment by IlkaCu** [comment]
I think it is okay to directly merge this to dev, otherwise we will face problems as soon as a later pandas version will be installed, right?

**Pull request merged**
