### PR TITLE
Features/#764 temporary set dependencies on ci

### LINKED ISSUE #764: Temporary dependencies to avoid problems with duplicate ids

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes #764 .

This is a PR for CI branch, because I couldn't add the dependencies on dev. 
I also reverted the commits from @fwitte in #757  which failed during the last CI-run.

### CODE REVIEW

**Comment by nesnoj** [comment]
Thanks for the fix, I'll start a test on SH..

**Comment by nesnoj** [comment]
- In `heat_etrago.buses` I get
`(psycopg2.errors.UndefinedTable) relation "demand.egon_etrago_timeseries_individual_heating" does not exist`
- In `hydrogen_etrago.power_to_h2.insert-power-to-h2-to-power` I get
`(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "egon_etrago_link_pkey"`

After clearing both tasks they run without errors, but `chp_etrago.insert` throws
```
Traceback (most recent call last):
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/storage/eGon-data-sh2/code/src/egon/data/datasets/chp_etrago.py", line 113, in insert
    chp_el["marginal_cost"] = get_sector_parameters("gas", "eGon2035")[
KeyError: 'gas_chp'
```

**Comment by ClaraBuettner** [comment]
> * In `heat_etrago.buses` I get
>       `(psycopg2.errors.UndefinedTable) relation "demand.egon_etrago_timeseries_individual_heating" does not exist`
> 

Thank you for your report, a dependency is missing. I will add this. 

>     * In `hydrogen_etrago.power_to_h2.insert-power-to-h2-to-power` I get
>       `(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "egon_etrago_link_pkey"`
> 
> 

This might be caused by the known problems with the eTraGo ids. Even if the eMob part is running after this task, other tasks can insert into the etrago tables in parallel and might cause these problems. 

> After clearing both tasks they run without errors, but `chp_etrago.insert` throws
> 
> ```
> Traceback (most recent call last):
>   File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
>     result = task_copy.execute(context=context)
>   File "/storage/eGon-data-sh2/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
>     result = super(type(task), task).execute(*xs, **ks)
>   File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
>     return_value = self.execute_callable()
>   File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
>     return self.python_callable(*self.op_args, **self.op_kwargs)
>   File "/storage/eGon-data-sh2/code/src/egon/data/datasets/chp_etrago.py", line 113, in insert
>     chp_el["marginal_cost"] = get_sector_parameters("gas", "eGon2035")[
> KeyError: 'gas_chp'
> ```

I think this problem was fixed in https://github.com/openego/eGon-data/commit/0878716abb6df203a637abcc4dd0d2c6794b24e6.

**Comment by nesnoj** [comment]
> > * In `heat_etrago.buses` I get
> >   `(psycopg2.errors.UndefinedTable) relation "demand.egon_etrago_timeseries_individual_heating" does not exist`
> 
> Thank you for your report, a dependency is missing. I will add this.

You haven't added this yet, have you?
I did it in 808e53e2c4abe8c98ea945f2e0b0de785bc66f50 , hope that's correct..

> > After clearing both tasks they run without errors, but `chp_etrago.insert` throws
> > ```
> > Traceback (most recent call last):
> >   File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
> >     result = task_copy.execute(context=context)
> >   File "/storage/eGon-data-sh2/code/src/egon/data/datasets/__init__.py", line 194, in skip_task
> >     result = super(type(task), task).execute(*xs, **ks)
> >   File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
> >     return_value = self.execute_callable()
> >   File "/storage/eGon-data-sh2/venv/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
> >     return self.python_callable(*self.op_args, **self.op_kwargs)
> >   File "/storage/eGon-data-sh2/code/src/egon/data/datasets/chp_etrago.py", line 113, in insert
> >     chp_el["marginal_cost"] = get_sector_parameters("gas", "eGon2035")[
> > KeyError: 'gas_chp'
> > ```
> 
> I think this problem was fixed in [0878716](https://github.com/openego/eGon-data/commit/0878716abb6df203a637abcc4dd0d2c6794b24e6).

I've cherry-picked this one.

I'll do a SH re-run..

**Review by nesnoj — APPROVED** [review]
With my changes, it works now

**Comment by ClaraBuettner** [comment]
The relevant commit was included in #795, so I will close this PR

**Pull request closed without merging**
