### PR TITLE
Features/#822 low flex scenario

### LINKED ISSUE #822: Create lowflex scenario
We discussed an (eTraGo) no-flex scenario several times in the past. Today, we agreed on creating it.
The main question is how to integrate it into the pipeline while keeping the time expenditure low. The cleanest way seems to be new scenario names such as `eGon2035_noflex`. We estimated that changing all steps that write into the `grid.egon_etrago_*` tables is too time-consuming do we decided to add a postprocessing step instead.

The questions that arise are: what needs to be changed for the several sectors/flex? Can the data from the existing scenarios just be duplicated, scenario name changed and some unnecessary components be dropped to create a noflex scenario? (e.g. storages for DSM) For many components this seems possible. If that's not possible for a flex, the eTraGo tables might need to be filled beforehand in the respective tasks.

@ClaraBuettner @IlkaCu @CarlosEpia @AmeliaNadal @fwitte 
I'd like to ask you to add the flex you're responsible for, whether a no-flex scenario can derived from the default scenario via postprocessing of the data in `grid.egon_etrago_*`, and required changes:

- DSM (@ClaraBuettner): **yes** - 
Drop stores with carrier 'dsm' from grid.egon_etrago_store and grid.egon_etrago_store_t, 
links with carrier 'dsm' from grid.egon_etrago_link and grid.egon_etrago_link_t, 
buses with carrier 'dsm' from grid.egon_etrago_bus 
- rural heat (@ClaraBuettner): **yes** - 
Drop stores with carrier '"rural_heat_store" from grid.egon_etrago_store, 
 links with carrier ["rural_heat_store_charger" , "rural_heat_store_discharger"] from grid.egon_etrago_link,  
 buses with carrier 'rural_heat_store' from grid.egon_etrago_bus 
- central heat (@ClaraBuettner): **yes** - 
Drop stores with carrier '"central_heat_store" from grid.egon_etrago_store, 
 links with carrier ["central_heat_store_charger" , "central_heat_store_discharger"] from grid.egon_etrago_link,  
 buses with carrier 'central_heat_store' from grid.egon_etrago_bus 
- emobility MIT (@nesnoj): **no** - Components need to be parametrized differently. Will be handled in the MIT dataset. #821.
- DLR (@CarlosEpia ): Yes.
No changes are required. If not values are passed for a scenario, it is assumed that the electrical transmission capacity is static.
- H2 (@AmeliaNadal): **yes**
For for both scenarios: Drop buses with carrier 'H2_saltcavern' from grid.egon_etrago_bus,
 all links related to these buses (carriers 'power_to_H2', 'H2_to_power') from grid.egon_etrago_link,
 and stores with carrier 'H2_underground' from grid.egon_etrago_store.
Drop links with carrier 'H2_gridextension' from grid.egon_etrago_link for eGon100RE.

### PR DESCRIPTION
**Pull request by nesnoj**
Fixes #822

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by nesnoj** [comment]
@IlkaCu as the low-flex task in the CI crashed on my SH instance, I fixed your script (just one semicolon missing). Consequently, I added this PR.

I will inject the fix into the CI on the Hetzner server (the task has not been reached yet).

**Comment by nesnoj** [comment]
Also, I fixed the emob-specific parts in your script in 7338337ec16c7d40f8a1a44734b058cd12a3e7cb (also injected on the server).

@IlkaCu Please review my changes and check the results thoroughly. Thx!

**Comment by nesnoj** [comment]
Can this be merged or is sth missing @ClaraBuettner @IlkaCu?

**Comment by ClaraBuettner** [comment]
> Can this be merged or is sth missing @ClaraBuettner @IlkaCu?

I think this is complete.

**Review by ClaraBuettner — APPROVED** [review]

**Pull request merged**
