### PR TITLE
Revise PR guidelines and contributing

### LINKED ISSUE #88: Revise PR guidelines
Review and maybe update PR guidelines in https://github.com/openego/eGon-data/blob/dev/CONTRIBUTING.rst

### LINKED ISSUE #145: Requesting reviews for PRs
During the intensive week some questions regarding PRs arose

- What needs to be reviewed? 
  - Just that the code working? 
  - That data is correct? 
  - That Tests pass? 
  - That documentation is up-to-date? 
  - That CHANGELOG is up-to-date
- Asking for a review
  - Asking for reviewing specific aspects helps reviewers a lot
  - When multiple people are asked for a review it should avoided that they check/test the same things

### PR DESCRIPTION
**Pull request by gplssm**
With these changes the CONTRIBUTING section in the documentation gets resorted, updated and extended. A special focus is on PRs and their reviews.

Fixes #88 
Fixes #145

### CODE REVIEW

**Comment by gplssm** [comment]
I tried to provide a practical solution to are discussion in the stand-up call today.

@AmeliaNadal for the review I would like to ask you to read through https://egon-data--147.org.readthedocs.build/en/147/contributing.html as give a general feedback if it makes sense to you. 
Please report aspects which you don't understand or which needs more clarification. If you find typos and fix the right away, I wouldn't mind ;-)

@ClaraBuettner I would like to ask you if there are important aspects missing in https://egon-data--147.org.readthedocs.build/en/147/contributing.html#pull-request-guidelines

Thank you :)

**Comment by ClaraBuettner** [comment]
I don't think that anything is missing. I'm just a bit confused by the point 

> Things that definitely should be checked during a review of a PR:
> ...
> Is the data correct? Verifying that newly integrated and processed data is correct is usually not possible during reviewing a PR. If it is necessary, please ask the reviewer specifically for this

That means that it doesn't needs to be checked during the review, but the title of the list indicates something different.

**Comment by AmeliaNadal** [comment]
I find the Contributing part very understandable and pretty well detailled, it is making sense to me!

**Comment by gplssm** [comment]
> I don't think that anything is missing. I'm just a bit confused by the point
> 
> > Things that definitely should be checked during a review of a PR:
> > ...
> > Is the data correct? Verifying that newly integrated and processed data is correct is usually not possible during reviewing a PR. If it is necessary, please ask the reviewer specifically for this
> 
> That means that it doesn't needs to be checked during the review, but the title of the list indicates something different.

True. It's not optimal here. I wanted to make sure that a reviewer has a look on these things and verifies that the contributor ticked all the check boxes. We can somehow reorganize this. But I don't have a really good idea at the moment... :thinking:

**Comment by gplssm** [comment]
I interpret your feedback as an approval :smiley:

**Pull request merged**
