### PR TITLE
Change H2 supply to H2_grid buses, import H2 from H2_saltcavern for loads within proximity of those buses

### LINKED ISSUE #481: There should be a function to handle generic voronoi cell creation
In the [gas_area.py](https://github.com/openego/eGon-data/blob/dev/src/egon/data/processing/gas_areas.py) file voronoi cell creation is handeled for H2 and CH4 carriers with individual functions. These are practically identical and can be reused easily. This might be useful for other voronoi routines, e.g. on the AC buses etc..

### LINKED ISSUE #620: Connect H2 loads to H2_grid system and H2_saltcavern in case of proximity
Open question: How does aggregation work with loads beeing connected non-uniformly to different H2 systems.

-> two H2 loads are in same H2_grid voronoi, one of them is connected to H2_saltcavern, the other is not.

### PR DESCRIPTION
**Pull request by fwitte**
Fixes #620 
Fixes #481 

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by fwitte** [comment]
The idea is to

- create separate voronoi cells for H2 systems
- connect loads to own H2 buses
- connect H2 buses of loads to respective H2_grid buses
- connect H2 buses of loads to H2_saltcavern buses in case proxmity criterion is met

With this going, #481 can finally be takled. Idea to use https://github.com/WZBSocialScienceCenter/geovoronoi instead of SQL. This might lighten the code significantly.

**Comment by fwitte** [comment]
I tested voronoi generation using the geovoronoi package, it produces identical areas (as expected, I guess). Will be integrated into the code like follows:

```python
coords = buses_CH4[["x", "y"]].values
area_shape = border.geometry.iloc[0]

region_polys, region_pts = voronoi_regions_from_coords(coords, area_shape)


fig, ax = plt.subplots(1)
border.plot(ax=ax)

gpd_input_dict= {
    'x': [],
    'y': [],
    'geometry': [],
    'original_id': []
}

for pt, poly in region_pts.items():
    gpd_input_dict['x'] += [coords[poly[0]][0]]
    gpd_input_dict['y'] += [coords[poly[0]][1]]
    gpd_input_dict['geometry'] += [region_polys[pt]]
    gpd_input_dict['original_id'] += [buses_CH4.iloc[poly[0]]["bus_id"]]


gdf_voronoi = gpd.GeoDataFrame(gpd_input_dict).set_index('original_id')
```

**Comment by fwitte** [comment]
Everything should work with the most recent changes, wil test run it locally and merge into CI tomorrow if it was successful.

**Comment by fwitte** [comment]
The parts directly change did run on CI and the data looks fine. Still ToDo:

- [ ] adjust capital cost for industry to cavern connection
- [ ] insert carrier into carrier table
- [ ] insert capital cost for pipeline extension in scenario_parameters table

**Comment by fwitte** [comment]
I accidentally ran black on the CH4_storages module @IlkaCu, no need to review that part :)

**Comment by fwitte** [comment]
Last open point: Should we actually consider pipeline extension here or just allow transport?

**Review by ClaraBuettner — APPROVED** [review]
I run this branch successfully in test mode

**Comment by fwitte** [comment]
> I run this branch successfully in test mode

Result on CI looks good as well.

**Pull request merged**
