### PR TITLE
Features/#486 update osm dataset

### LINKED ISSUE #486: Update OSM dataset
Update OSM (currentl 01.01.2021) to a newer version, cf. https://github.com/openego/eGon-data/issues/435#issuecomment-952654765 to have a recent building dataset available.

May lead to osmTGmod issues, integration needs to be checked thoroughly.

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes #486  .

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by nesnoj** [comment]
Yea, thanks for tackling the update! Not sure how u use "Draft" - is this ready for review?

**Comment by ClaraBuettner** [comment]
> Yea, thanks for tackling the update! Not sure how u use "Draft" - is this ready for review?

I marked it as "draft" because it is not tested for Germany yet. We don't have another instance to run this test, so I have to wait for the next CI-run. But the code should be done.

**Comment by nesnoj** [comment]
The task `fix_ehv_subnetworks` failed:
```
TypeError: add_line() takes 7 positional arguments but 9 were given
```

**Comment by ClaraBuettner** [comment]
> The task `fix_ehv_subnetworks` failed:
> 
> ```
> TypeError: add_line() takes 7 positional arguments but 9 were given
> ```

Thank you for the remark, I fixed it in a4e9907e256ac96f8ae695fd8b307d39b4a95981 
The task was now running successfully on CI-branch

**Review by nesnoj — APPROVED** [review]
I checked some numbers of OSM buildings and downstream results, looks fine to me.

I updated the changelog and applied black+isort. However, flake8 issued several problems in `fix_ehv_subnetworks.py` that require manual attention (which I overrode)... could pls u check them?

**Comment by ClaraBuettner** [comment]
> I checked some numbers of OSM buildings and downstream results, looks fine to me.
> 
> I updated the changelog and applied black+isort. However, flake8 issued several problems in `fix_ehv_subnetworks.py` that require manual attention (which I overrode)... could pls u check them?

Thank you! I didn't check `flake8` before and just used` black`. But I fixed the problems, it should be fine now.

**Comment by nesnoj** [comment]
Thx, feel free to merge :)

**Pull request merged**
