### PR TITLE
Assign voltage level and bus_id to power plants

### LINKED ISSUE #174: Add MaStR Lokationen data
Information about locations of power plant facilities is needed to decide on the grid connection points

### PR DESCRIPTION
**Pull request by ClaraBuettner**
This branch adds voltage level and bus_ids to power plants (see #15), since I needed the mastr location data, I adjusted the mastr download, so this closes #174.

@gplssm Could you check if the location data is downloaded correctly? (I tried it and it worked, I just want to be sure to have the correct deposit_id.)

### CODE REVIEW

**Review by gplssm — CHANGES_REQUESTED** [review]
Thanks for implementing this!

I scrolled through the changes and it looks plausible. 

You chose the correct deposit id.
In order to verify that the download of MaStR from Zenodo works correctly, I execute the workflow locally. It could check it, because I ran into an error: the task `create-landuse-table` fails because the openstreetmap schema isn't defined (it's a fresh DB). 

grafik

I think, this task should somehow depend on the osm downloading/importing tasks...

In addition, you should consider to write a short note in the CHANGELOG.

**Comment by ClaraBuettner** [comment]
> Thanks for implementing this!
> 
> I scrolled through the changes and it looks plausible.
> 
> You chose the correct deposit id.

Thank you for checking this!
> In order to verify that the download of MaStR from Zenodo works correctly, I execute the workflow locally. It could check it, because I ran into an error: the task `create-landuse-table` fails because the openstreetmap schema isn't defined (it's a fresh DB).
> I think, this task should somehow depend on the osm downloading/importing tasks...

This tasks was added in another commit and is not related to this PR. Anyhow I could fix it in this branch, or we open a new issue/branch/PR.

**Review by IlkaCu — APPROVED** [review]
I tested the branch on a fresh database for 'Schleswig-Holstein' and it worked well.

**Comment by gplssm** [comment]
> I tested the branch on a fresh database for 'Schleswig-Holstein' and it worked well.

Thanks! I had multiple failing, obviously due to other reasons... So, please merge!

**Pull request merged**
