### PR TITLE
Fix zensus weather cell mapping

### LINKED ISSUE #1031: Fix zensus weather cells mapping
We discovered in #684 that census cells are missing in the mapping table `boundaries.egon_map_zensus_weather_cell` as only populated census cells are used. For rooftop pv also unpopulated cells with CTS buildings get pv assigned. Therefore the mapping table needs to be adapted to all census cells.

### PR DESCRIPTION
**Pull request by nailend**
Fixes #1031.

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted.
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Review by khelfen — APPROVED** [review]
In my current run everything worked and the changes look good :+1:

**Comment by nailend** [comment]
> In my current run everything worked and the changes look good :+1: 

Great, was a DE run, wasn't it?

**Comment by khelfen** [comment]
> > In my current run everything worked and the changes look good +1
> 
> Great, was a DE run, wasn't it?

Unfortunately no. I can't get a DE run to work atm (failing at `zensus.zensus-misc-to-postgres` now :roll_eyes: )

**Comment by nesnoj** [comment]
Can this be merged?

**Comment by nesnoj** [comment]
At least it ran successfully on the Flensburg server. But I did not check any results.

**Pull request merged**
