### PR TITLE
Features/#331 small chp extension

### LINKED ISSUE #331: Distribute CHP plants < 10MW
CHP plants < 10MW_el are not allocated in the NEP list of conventional power plants. 
The existing locations from MaStR are used for the existing CHP < 10MW. Additional plants in the future scenarios get new locations, e.g. based on district heating areas.

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Closes #331 

This branch adds the distribution of additional CHP < 10MW. 
New CHP plants are build for district heating (including "Nahwärme") and industrial areas. The share of district heating and industrial CHP from today per federal state is used to forecast the future shares. 
There is one task per federal state, so only one task in test-mode but 16 when running it for Germany. It is already tested for both Schleswig-Holstein and Germany. 
For the parallel tasks I had to cherry-pick some commits from #443 so it would be good if this PR is merged afterwards.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
@AmeliaNadal This feature-branch already run several times on the CI-branch, so I think it's okay if you don't execute it again.

**Comment by AmeliaNadal** [comment]
The chp.extension-SH task failed, because 'gas_bus_id' is an invalid keyword argument for EgonChp. Indeed, I've modified the EgonChp class:
https://github.com/openego/eGon-data/blob/5858cd027831b2c0f49b85aad7c88891305c6455/src/egon/data/datasets/chp/__init__.py#L32
Should I adjust the function extension_to_areas?
https://github.com/openego/eGon-data/blob/5858cd027831b2c0f49b85aad7c88891305c6455/src/egon/data/datasets/chp/small_chp.py#L250

**Comment by ClaraBuettner** [comment]
> The chp.extension-SH task failed, because 'gas_bus_id' is an invalid keyword argument for EgonChp. Indeed, I've modified the EgonChp class:
> 
> https://github.com/openego/eGon-data/blob/5858cd027831b2c0f49b85aad7c88891305c6455/src/egon/data/datasets/chp/__init__.py#L32
> 
> Should I adjust the function extension_to_areas?
> 
> https://github.com/openego/eGon-data/blob/5858cd027831b2c0f49b85aad7c88891305c6455/src/egon/data/datasets/chp/small_chp.py#L250

Thank you for the remark! I already solved this on the CI-branch but forgot to do it again on this branch. It's fixed now.

**Comment by ClaraBuettner** [comment]
I run this branch in test mode and all tasks finished successfully. Could you post the error message?

**Comment by AmeliaNadal** [comment]
> 
> 
> I run this branch in test mode and all tasks finished successfully. Could you post the error message?

```
*** Reading local file: /opt/egon_data_workflow/wd_test_mode/airflow/logs/egon-data-processing-pipeline/chp.extension-SH/2021-10-04T14:31:04.055392+00:00/2.log
[2021-10-05 09:03:45,206] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.chp.extension-SH 2021-10-04T14:31:04.055392+00:00 [queued]>
[2021-10-05 09:03:45,353] {taskinstance.py:670} INFO - Dependencies all met for <TaskInstance: egon-data-processing-pipeline.chp.extension-SH 2021-10-04T14:31:04.055392+00:00 [queued]>
[2021-10-05 09:03:45,353] {taskinstance.py:880} INFO - 
--------------------------------------------------------------------------------
[2021-10-05 09:03:45,353] {taskinstance.py:881} INFO - Starting attempt 2 of 2
[2021-10-05 09:03:45,353] {taskinstance.py:882} INFO - 
--------------------------------------------------------------------------------
[2021-10-05 09:03:45,388] {taskinstance.py:901} INFO - Executing <Task(Chp (versioned)): chp.extension-SH> on 2021-10-04T14:31:04.055392+00:00
[2021-10-05 09:03:45,402] {standard_task_runner.py:54} INFO - Started process 24367 to run task
[2021-10-05 09:03:45,509] {standard_task_runner.py:77} INFO - Running: ['airflow', 'run', 'egon-data-processing-pipeline', 'chp.extension-SH', '2021-10-04T14:31:04.055392+00:00', '--job_id', '3638', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/dags/pipeline.py', '--cfg_path', '/tmp/tmpp051rjrr']
[2021-10-05 09:03:45,511] {standard_task_runner.py:78} INFO - Job 3638: Subtask chp.extension-SH
[2021-10-05 09:03:45,654] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.chp.extension-SH 2021-10-04T14:31:04.055392+00:00 [running]> on host torch.esy.ve.dlr
[2021-10-05 09:03:46,694] {logging_mixin.py:120} INFO - Target capacity in SchleswigHolstein: 300.0
[2021-10-05 09:03:46,695] {logging_mixin.py:120} INFO - Existing capacity in SchleswigHolstein: 151.8315
[2021-10-05 09:03:46,698] {logging_mixin.py:120} INFO - Distributing 148.1685 MW_el in SchleswigHolstein
[2021-10-05 09:03:46,698] {logging_mixin.py:120} INFO - Distributing 108.83255742286678 MW_el to district heating
[2021-10-05 09:03:50,058] {utils.py:145} INFO - Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
[2021-10-05 09:03:50,059] {utils.py:157} INFO - NumExpr defaulting to 8 threads.
[2021-10-05 09:03:54,943] {logging_mixin.py:120} WARNING - /home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)
[2021-10-05 09:10:27,993] {logging_mixin.py:120} INFO - Distributing 39.3359425771332 MW_el to industry
[2021-10-05 09:11:46,024] {taskinstance.py:1150} ERROR - Some power plants are
    not attached to a bus:           demand  osm_id  ... voltage_level bus_id
264  8382.894241  398305  ...           6.0    NaN

[1 rows x 7 columns]
Traceback (most recent call last):
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/__init__.py", line 195, in skip_task
    result = super(type(task), task).execute(*xs, **ks)
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nada_am/anaconda3/envs/egondata_l/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/__init__.py", line 298, in extension_SH
    extension_per_federal_state("SchleswigHolstein", EgonChp)
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/small_chp.py", line 592, in extension_per_federal_state
    not_distributed_capacity_industry = extension_industrial(
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/small_chp.py", line 495, in extension_industrial
    not_distributed_capacity = extension_to_areas(
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/chp/small_chp.py", line 216, in extension_to_areas
    selected_areas.loc[:, "bus_id"] = assign_bus_id(
  File "/opt/egon_data_workflow/egondata_test_mode/eGon-data/src/egon/data/datasets/power_plants/__init__.py", line 526, in assign_bus_id
    assert power_plants.bus_id.notnull().all(), f"""Some power plants are
AssertionError: Some power plants are
    not attached to a bus:           demand  osm_id  ... voltage_level bus_id
264  8382.894241  398305  ...           6.0    NaN

[1 rows x 7 columns]
[2021-10-05 09:11:46,028] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=chp.extension-SH, execution_date=20211004T143104, start_date=20211005T070345, end_date=20211005T071146
[2021-10-05 09:11:48,609] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by ClaraBuettner** [comment]
This problem can be also caused by incomplete or outdated mv grid districts. Can you check if the mv grid district tasks was skipped or start a clean run to make sure that all tasks are executed again?

**Comment by IlkaCu** [comment]
I started a local clean run and task `chp_etrago.insert` failed due to some renaming issues: 

```
LINE 2:         SELECT electrical_bus_id, gas_bus_id, a.carrier,
                                          ^
HINT:  Perhaps you meant to reference the column "a.ch4_bus_id".
```

**Comment by IlkaCu** [comment]
Claras commit fixed the mentioned problem and the named task succeeded. From my point of view this feature could and should be merged soon.

**Review by AmeliaNadal — APPROVED** [review]

**Comment by fwitte** [comment]
I have the identical error message in my installation (same server...).

**Pull request merged**
