### PR TITLE
Fix using datasets ending with parallel tasks as dependencies

### LINKED ISSUE #365: Dependencies of datasets ending with parallel tasks are not set correctly
I added the HeatSupply-dataset, which ends with three parallel tasks: 
https://github.com/openego/eGon-data/blob/26df9093bb6b1d1908bd8dbdd85c02d719cf88ea/src/egon/data/datasets/heat_supply/__init__.py#L110-L118

Another dataset (HeatEtrago) depends on the HeatSupply-dataset: 
https://github.com/openego/eGon-data/blob/26df9093bb6b1d1908bd8dbdd85c02d719cf88ea/src/egon/data/airflow/dags/pipeline.py#L617-L618

But when I set the dependency only like this, the tasks of HeatEtrago run before all tasks of HeatSupply are completed. This results into errors. So I added a dependency in the old syntax to solve this temporary. 

The same problem occurs in other datasets (on a feature-branch) which end with parallel tasks.

### PR DESCRIPTION
**Pull request by gnn**
This should fix #365. It's not tested in `continuous-integration/run-everything-over-the-weekend` yet, because I also didn't get around to run the test mode on it, yet. I hope I'll manage to do so before Friday, so the changes can be teste over the weekend. But you can already have  look and tell whether any of these changes look wrong.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
Looks good, thank you! I can also run it in test mode if you like. 
And I also know that there are other datasets which could use parallel tasks (society_prognosis, demandregio). Should I also change them on this branch?

**Comment by gnn** [comment]
> Looks good, thank you! I can also run it in test mode if you like.

Oh, that would be really nice. I don't know whether I'll get around to it today, so if you could check that it runs in test mode, that would be really awesome.

> And I also know that there are other datasets which could use parallel tasks (society_prognosis, demandregio). Should I also change them on this branch?

I think that would be a good idea. That way we know that the fix works for all the cases. Also, there's one more change I'd like to make and then there won't be any unpleasant surprises with that one, either.

**Comment by nesnoj** [comment]
> I think that would be a good idea. That way we know that the fix works for all the cases. Also, there's one more change I'd like to make and then there won't be any unpleasant surprises with that one, either.

I'll adjust the building/street extraction too. But as my branch `features/#262-preprocess-osm-buildings-amenities` is not part of `dev` yet, I'll adjust it there and merge it into the weekend branch..

**Comment by ClaraBuettner** [comment]
> Oh, that would be really nice. I don't know whether I'll get around to it today, so if you could check that it runs in test mode, that would be really awesome.
> 
I just started a run and will let you now if everything worked. 


> I think that would be a good idea. That way we know that the fix works for all the cases. Also, there's one more change I'd like to make and then there won't be any unpleasant surprises with that one, either.

Ok, I will wait for your change and then commit and push the update for demandregio and society_prognosis.

**Comment by ClaraBuettner** [comment]
I run into one problem (see #444) which I temporary solved with https://github.com/openego/eGon-data/pull/443/commits/29e1af37d865112853960660ed3f5fbb5657af1f  
All other tasks run successful in a clean run in test mode. So I think this can be merged into `continuous-integration/run-everything-over-the-weekend`.

**Comment by gnn** [comment]
Merged into the weekend CI branch and started it.

**Comment by gnn** [comment]
If I'm reading the DAG run correctly, there where no errors related to this, so I can merge it into `dev`, right?

**Review by ClaraBuettner — APPROVED** [review]

**Comment by ClaraBuettner** [comment]
@gnn Could this be merged into `dev` or is there still something to do?

**Pull request merged**
