### PR TITLE
Features/#198-Integration_of_gas_busss_and_links

### PR DESCRIPTION
**Pull request by AmeliaNadal**
#198 
Integration of the gas buses and links from the SciGRID_gas data.

### CODE REVIEW

**Comment by ClaraBuettner** [comment]
I tried to run this branch but run into an error inside the download_SciGRID_gas_data-task. I can't find any new downloaded zip file in the current working directory or src/egon/data/importing/gas_grid.

```

> [2021-05-25 16:56:13,583] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.insert-gas-grid 2021-05-25T14:55:37.002721+00:00 [running]> on host clara-LIFEBOOK-U749
> [2021-05-25 16:56:15,432] {taskinstance.py:1150} ERROR - [Errno 2] No such file or directory: 'src/egon/data/importing/gas_grid/IGGIELGN.zip'
> Traceback (most recent call last):
>   File "/home/clara/test-egon-data/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
>     result = task_copy.execute(context=context)
>   File "/home/clara/test-egon-data/venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
>     return_value = self.execute_callable()
>   File "/home/clara/test-egon-data/venv/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
>     return self.python_callable(*self.op_args, **self.op_kwargs)
>   File "/home/clara/test-egon-data/git/eGon-data/src/egon/data/importing/gas_grid/__init__.py", line 264, in insert_gas_data
>     download_SciGRID_gas_data()
>   File "/home/clara/test-egon-data/git/eGon-data/src/egon/data/importing/gas_grid/__init__.py", line 28, in download_SciGRID_gas_data
>     urlretrieve(zenodo_zip_file_url, path + 'IGGIELGN.zip')
>   File "/home/clara/miniconda3/lib/python3.7/urllib/request.py", line 257, in urlretrieve
>     tfp = open(filename, 'wb')
> FileNotFoundError: [Errno 2] No such file or directory: 'src/egon/data/importing/gas_grid/IGGIELGN.zip'
> [2021-05-25 16:56:15,440] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=insert-gas-grid, execution_date=20210525T145537, start_date=20210525T145613, end_date=20210525T145615
> [2021-05-25 16:56:18,298] {local_task_job.py:102} INFO - Task exited with return code 1

```

**Comment by ClaraBuettner** [comment]
Now it is working and the results are plausible!
I'm just wondering if it might make sense to store the buses and links directly in the egon_pf_hv_bus and ..._link tables. What do you think @AmeliaNadal?

**Comment by ClaraBuettner** [comment]
@AmeliaNadal please write me if I should test this branch again.
And could you also write a short note into the [changelog](https://github.com/openego/eGon-data/blob/dev/CHANGELOG.rst)?

**Comment by AmeliaNadal** [comment]
@ClaraBuettner I am still struggeling with resolving the conflicts, can we call again today please?

**Review by ClaraBuettner — APPROVED** [review]
I tested the branch again and your task run successfully

**Pull request merged**
