### PR TITLE
Add dependency to heat_etrago

### LINKED ISSUE #771: Missing dependency for heat_etrago.bus
It seems that a dependency for for heat_etrago.bus is missing. When running dev in SH mode on my local machine it says that relation "demand.egon_etrago_timeseries_individual_heating" does not exist

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Fixes #771 .

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [ ] _the `Dataset`-version is updated when existing datasets are adjusted._ No dataset was adjusted
- [x] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [ ] _the workflow is running successful in `test mode`._  I only added a dependency so I'm not sure if that's necessary.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Review by nesnoj — APPROVED** [review]
LGTM

**Comment by nesnoj** [comment]
Merge to CI if you think that's required...

**Comment by nesnoj** [comment]
> Merge to CI if you think that's required...

I did it

**Comment by ClaraBuettner** [comment]
> > Merge to CI if you think that's required...
> 
> I did it

Thank you!

**Pull request merged**
