### PR TITLE
Integrate weather data and feedin timeseries

### LINKED ISSUE #123: Create table for weather-dependent feed-in time series
A table to store weather-dependent time series for the electricity generation of PV and wind power plants per weather grid cell needs to be created. 
It could look like this: 
```
class EgonReFeedIn(Base):
    __tablename__ = 'egon_re_feed_in'
    __table_args__ = {'schema': 'supply'}
    w_id = Column(Integer)
    weather_year = Column(Integer)
    carrier = Column(String)
    feedin = Column(ARRAY(Float()))
```

### PR DESCRIPTION
**Pull request by ClaraBuettner**
Closes #123 , partly solves #19 
This branch adds the download of weather data and creation of feed in time series for wind onshore, pv and solar thermal. 
Since we haven't agreed on parameters for solar thermal and pv yet, I used the ones from pypsa-eur-sec. But this can be adjusted easily. 
Time series for wind offshore and hydro are currently missing due to additional input data sets.

### CODE REVIEW

**Comment by IlkaCu** [comment]
The following error occurs when executing the `insert-feedin` scripts: 
```
[2021-05-06 13:24:24,296] {standard_task_runner.py:78} INFO - Job 1196: Subtask insert-feedin-solar-thermal
[2021-05-06 13:24:24,348] {logging_mixin.py:112} INFO - Running <TaskInstance: egon-data-processing-pipeline.insert-feedin-solar-thermal 2021-05-05T15:07:10.205751+00:00 [running]> on host ilka-LIFEBOOK-U749
[2021-05-06 13:24:25,024] {cutout.py:76} INFO - Cutout europe-2011-era5 not found in directory /home/ilka/egon-data-test/cutouts, building new one
[2021-05-06 13:24:25,297] {api.py:517} INFO - Welcome to the CDS
[2021-05-06 13:24:25,297] {api.py:517} INFO - Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-single-levels
[2021-05-06 13:24:25,398] {api.py:517} INFO - Request is queued
[2021-05-06 13:36:46,081] {api.py:517} INFO - Request is completed
[2021-05-06 13:36:46,082] {era5.py:85} INFO - Downloading request for 9 variables to /tmp/tmp2yd92qsn.nc
[2021-05-06 13:36:46,083] {api.py:517} INFO - Downloading https://download-0007.copernicus-climate.eu/cache-compute-0007/cache/data0/adaptor.mars.internal-1620300993.3801265-31086-16-b06025e8-8fe3-4771-9d84-be3363066065.nc to /tmp/tmp2yd92qsn.nc (6.8K)
[2021-05-06 13:36:46,456] {logging_mixin.py:112} WARNING - 
  0%|          | 0.00/6.84k [00:00<?, ?B/s]
[2021-05-06 13:36:46,456] {logging_mixin.py:112} WARNING - 
                                           
[2021-05-06 13:36:46,456] {api.py:517} INFO - Download rate 18.4K/s
[2021-05-06 13:36:46,730] {taskinstance.py:1150} ERROR - The cutout has to be prepared first.
Traceback (most recent call last):
  File "/home/ilka/virtuelle_Umgebungen/eGon-data/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ilka/virtuelle_Umgebungen/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/ilka/virtuelle_Umgebungen/eGon-data/lib/python3.8/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ilka/eGon-data/src/egon/data/processing/renewable_feedin/__init__.py", line 266, in solar_thermal_feedin_per_weather_cell
    ts_solar_thermal = cutout.solar_thermal(
  File "/home/ilka/virtuelle_Umgebungen/eGon-data/lib/python3.8/site-packages/atlite/convert.py", line 343, in solar_thermal
    return cutout.convert_and_aggregate(convert_func=convert_solar_thermal,
  File "/home/ilka/virtuelle_Umgebungen/eGon-data/lib/python3.8/site-packages/atlite/convert.py", line 109, in convert_and_aggregate
    assert cutout.prepared, "The cutout has to be prepared first."
AssertionError: The cutout has to be prepared first.
[2021-05-06 13:36:46,736] {taskinstance.py:1187} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=insert-feedin-solar-thermal, execution_date=20210505T150710, start_date=20210506T112423, end_date=20210506T113646
[2021-05-06 13:36:50,734] {local_task_job.py:102} INFO - Task exited with return code 1
```

**Comment by ulfmueller** [comment]
if one has followed the instructions for the installation of the copernicus weather data website AND agreed on the terms of use it works fine. Please add the link for the term agreement to the readme because it was very hidden and only if one would read the error notice well enough one gets to the right web link.

**Review by IlkaCu — APPROVED** [review]
I had to mark the download tasks manually as success, but beside from this everything worked well.

**Comment by nesnoj** [comment]
A registration at CDS is required to execute the job `download-weather-data`.
Could you please add a short note to the getting started docs on registration, required [explicit agreement](https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products) and .cdsapirc file?

**Comment by ClaraBuettner** [comment]
> A registration at CDS is required to execute the job `download-weather-data`.
> Could you please add a short note to the getting started docs on registration, required [explicit agreement](https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products) and .cdsapirc file?
> Thx!

There is already a short note in the Pre-requisites: 
* To download ERA5 weather data you need to register at the CDS
  registration page and install the CDS API key as described
  `here <https://cds.climate.copernicus.eu/api-how-to>`_
  You also have to agree on the `terms of use 
  <https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products>`_

Do you want me to move this note to another section and/or explain it more in detail?

**Comment by nesnoj** [comment]
\*cough\* \*cough\* I checked the getting started and searched the docs for some keywords but apparently at some days it might be better to finish work at 5pm.. sorry for the false alert and thank you for the note, it looks sufficient as it is :)

**Pull request merged**
