### PR TITLE
Fill missing household data for populated cells

### LINKED ISSUE #431: Zensus cells without HH demand profiles
Maybe I was too fast merging #260 :

Some Zensus cells with buildings and population do not have any profiles assigned. Let's consider this example plot (village: Husby, east of Flensburg):

image

Legend:
- green cells: zensus cells **with** profiles assigned
- red cells: zensus cells **without** profiles assigned
- numbers: population and number of households from zensus
- brown: buildings

Obviously, there're no profiles assigned in cells without data on households - the methods do not cover those edge cases. In ding0 the buildings won't be part of the grid as they have no load. This might be acceptable in the example above but I've seen settlements with a handful of cells and only 1 holding profile information...

Is there a quick way of covering those edge cases, e.g. use the population (we had a similar case for a missing attribute, cf. [post](https://github.com/openego/eGon-data/pull/260#issuecomment-887586406)) and some average HH distribution?

### PR DESCRIPTION
**Pull request by nailend**
Fixes #431 . 

We decided to go for a random choice distribution within subgroups of specific population.
All cells which have a specific population value and no household distribution data, will get the same household distribution applied which is taken from a random cell with the same population value.

## Before merging into `dev`-branch, please make sure that

- [x] the `CHANGELOG.rst` was updated.
- [x] new and adjusted code is formated using `black` and `isort`.
- [x] the `Dataset`-version is updated when existing datasets are adjusted. 
- [x] the branch was merged into the `continuous-integration/run-everything-over-the-weekend`- branch.
- [x] the workflow is running successful in `test mode`.
- [x] the workflow is running successful in `Everything` mode.

### CODE REVIEW

**Comment by nesnoj** [comment]
Thanks for the fix!
Are the results reproducible? You incorporate random seed but is the list you are sampling from always in the same order?

**Comment by nailend** [comment]
> Thanks for the fix! Are the results reproducible? You incorporate random seed but is the list you are sampling from always in the same order?

The list should only change depending on the cut-out. Here is the [Sampling](https://github.com/openego/eGon-data/blob/67fff19dded54796dd0fc1c59521459e207d7649/src/egon/data/datasets/electricity_demand_timeseries/hh_profiles.py#L730). It could change if the SQL-Query changes the return, does it?

**Comment by ClaraBuettner** [comment]
There are still some cells with population but without households. I run the sql statement in https://github.com/openego/eGon-data/pull/558#issuecomment-996705984 and found 11 cells with a population but no entry in `demand.egon_household_electricity_profile_of_buildings`:
I thought that this should not happen anymore or did I used the wrong table? 
image

For all these cells there is no other cell with the same population value. According to the explanation of how you assign households to the cells this could be a problem.

**Comment by nesnoj** [comment]
> There are still some cells with population but without households. I run the sql statement in [#558 (comment)](https://github.com/openego/eGon-data/pull/558#issuecomment-996705984) and found 11 cells with a population but no entry in `demand.egon_household_electricity_profile_of_buildings`:
> I thought that this should not happen anymore or did I used the wrong table?

Thanks for checking! Did you run the latest version? And: SH or DE?

**Comment by ClaraBuettner** [comment]
> Thanks for checking! Did you run the latest version? And: SH or DE?

I used the data from the latest CI-run, so it's data for Germany and I think it's also the latest version

**Comment by nesnoj** [comment]
> > Thanks for checking! Did you run the latest version? And: SH or DE?
> 
> I used the data from the latest CI-run, so it's data for Germany and I think it's also the latest version

If you did not re-pull and -run it again this week @ClaraBuettner , the run on the Flensburg server did not include the latest fixes, esp. 1116bc177efc8283e5caaf63d37ef14353dbc768, right @nailend? 
I started a new DE run on our workstation and will post the query's results as soon as the tasks are finished...

**Comment by nesnoj** [comment]
Here come the results:

## 1.
```sql
SELECT COUNT(egon_profiles.cell_id) as egon_hh_cells, count(t3.id_pop) as zenus_cells, count(t1.zensus_population_id) as peta_cells
FROM demand.egon_household_electricity_profile_in_census_cell as egon_profiles

FULL JOIN (
	SELECT id as id_pop
		FROM society.destatis_zensus_population_per_ha
		WHERE population > 0) as t3
	on egon_profiles.cell_id = t3.id_pop


FULL JOIN (
	SELECT zensus_population_id
		FROM demand.egon_peta_heat 
		WHERE sector = 'residential' ) as t1
		on egon_profiles.cell_id = t1.zensus_population_id;
```
returns

image

## 2.

> There are still some cells with population but without households. I run the sql statement in [#558 (comment)](https://github.com/openego/eGon-data/pull/558#issuecomment-996705984) and found 11 cells with a population but no entry in `demand.egon_household_electricity_profile_of_buildings`:
> I thought that this should not happen anymore or did I used the wrong table?

Now the query result is empty :)

**Comment by ClaraBuettner** [comment]
> Here come the results:
> ## 1.
> 
> ```sql
> SELECT COUNT(egon_profiles.cell_id) as egon_hh_cells, count(t3.id_pop) as zenus_cells, count(t1.zensus_population_id) as peta_cells
> FROM demand.egon_household_electricity_profile_in_census_cell as egon_profiles
> 
> FULL JOIN (
> 	SELECT id as id_pop
> 		FROM society.destatis_zensus_population_per_ha
> 		WHERE population > 0) as t3
> 	on egon_profiles.cell_id = t3.id_pop
> 
> 
> FULL JOIN (
> 	SELECT zensus_population_id
> 		FROM demand.egon_peta_heat 
> 		WHERE sector = 'residential' ) as t1
> 		on egon_profiles.cell_id = t1.zensus_population_id;
> ```
> 
> returns
> 
> image
> ## 2.
> 
> > There are still some cells with population but without households. I run the sql statement in [#558 (comment)](https://github.com/openego/eGon-data/pull/558#issuecomment-996705984) and found 11 cells with a population but no entry in `demand.egon_household_electricity_profile_of_buildings`:
> > I thought that this should not happen anymore or did I used the wrong table?
> 
> Now the query result is empty :)

That looks great, thank you!
 I'm sorry for my confusion, I misunderstood the ticked 'the workflow is running successful in Everything mode.' option...

**Review by nesnoj — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
